project:
  type: book
  output-dir: docs

book:
  title: "Data i Dialog - basutbud"
  repo-url: "https://github.com/pgmj/DIDbasutbud"
  sidebar:
    style: floating
    search: true
  author:
    - name: 'Magnus Johansson'
      affiliation: 'RISE Research Institutes of Sweden'
      affiliation-url: 'https://ri.se/shic'
      orcid: '0000-0003-1669-592X'
    - name: 'Marit Preuter'
      affiliation: 'RISE Research Institutes of Sweden'
      affiliation-url: 'https://ri.se/shic'
  date: last-modified
  date-format: iso
  chapters:
  - index.qmd
  - fldr.qmd
  - skola.qmd
  - fritid.qmd
  - community.qmd

format:
  html:
    toc: true
    toc-depth: 3
    code-tools: false
    code-fold: true
    number-sections: true
    layout-align: left
    page-layout: full
    mainfont: 'Lato'
    monofont: 'Roboto Mono'
    linestretch: 1.6
    theme:
      - materia
      - custom.scss
    css: styles.css
    link-external-newwindow: true
    fig-dpi: 96
    crossref-sec-prefix: "Sektion"
    toc-title: "Innehållsförteckning"
    crossref-fig-title: "Figur"
    crossref-tbl-title: "Tabell"
    callout-note-title: "Beskrivning"

execute:
  echo: false
  warning: false
  message: false
  cache: false
