---
title-block-banner: "#2D6B97"
title-block-banner-color: "#BBDBEC"
title: "Tryggt närsamhälle"
---

## Definition Skyddsfaktor

Ett tryggt närsamhälle är en skyddsfaktor som innefattar flera fysiska, sociala och ekologiska aspekter som tillsammans kan bidra till att främja goda uppväxtvillkor. Forskning visar att villkoren i områden där barn växer upp har betydelse för identitetsskapande och möjligheter senare i livet.

Social tillit och trygghet påverkas av hur bostadsområden är utformade och hur områdena hänger samman med det övriga samhället. Social tillit bidrar även till en mer effektiv social kontroll eftersom invånare som känner sig trygga och delaktiga är mer benägna att följa samhällets normer och regler och agera för att upprätta hålla dessa. Trygghetsvandringar, tillgång till mötesplatser, närvaro av samhällsservice i området samt dialoger med medborgare, inklusive barn och unga, bidrar till att utveckla den sociala tilliten i området.

Läs mer på [Boverket](https://www.boverket.se/sv/samhallsplanering/stadsutveckling/halsa-forst/social-inkludering/tillit-och-trygghet/)


## Underlag för verksamhetskartläggning och analys av *ett tryggt närsamhälle* 

### Konventionen om barnets rättigheter

Flera artiklar i barnkonventionen stödjer och vägleder i att skapa ett tryggt närsamhälle. Nedan listas ett urval av artiklar som ger stöd för de främjande och förebyggande insatser som kan behöva utvecklas i arbetet med att skapa ett tryggt närsamhälle:

- **Artikel 3:** Barnets bästa ska beaktas vid alla beslut som rör barn. Beslut som påverkar barn och unga i närsamhället ska alltid ta hänsyn till deras bästa och säkerställa att deras välmående prioriteras.

-	**Artikel 6:** Rätt till liv, överlevnad och utveckling. Barn har rätt att leva och utvecklas under goda och säkra förhållanden, vilket innebär att närsamhället behöver erbjuda en trygg och stödjande miljö.

-	**Artikel 12:** Rätt att uttrycka sina åsikter och bli hörda. Barn och unga ska ha möjlighet att uttrycka sina åsikter i frågor som rör dem och deras åsikter ska beaktas i beslutsprocesser som påverkar deras uppväxtmiljö.

-	**Artikel 19:** Skydd mot våld, övergrepp och försummelse. Barn ska skyddas mot alla former av våld, skada eller övergrepp, vilket innebär att närsamhället behöver vara säkert och fritt från våld.

-	**Artikel 24:** Rätt till bästa uppnåeliga hälsa. Barn har rätt till god hälsa och sjukvård, vilket inkluderar tillgång till hälsofrämjande miljöer och resurser i närsamhället, samt ett aktivt arbete för att avskaffa sedvänjor som är skadliga. 

-	**Artikel 27:** Rätt till en skälig levnadsstandard. Barn har rätt till en levnadsstandard som är tillräcklig för deras fysiska, mentala, andliga, moraliska och sociala utveckling. Detta innebär att närsamhället ska stödja ansvariga vårdnadshavare i att möjliggöra detta.  

-	**Artikel 31:** Rätt till vila, fritid och lek. Närsamhället ska erbjuda säkra och tillgängliga platser för vila, rekreation och lek.

-	**Artikel 34:** Skydd mot sexuellt utnyttjande och sexuella övergrepp. Barn ska skyddas mot alla former av sexuellt utnyttjande och övergrepp, vilket kräver en trygg och säker miljö i närsamhället.

### Lag (2023:196) om kommuners ansvar för brottsförebyggande arbete

Lagen om kommuners ansvar för brottsförebyggande arbete innebär att varje kommun ska bedriva ett kunskapsbaserat brottsförebyggande arbete och säkerställa organisatoriska förutsättningar för det. Målet är att skapa ökad trygghet och minska brottsligheten. Kommunerna ska kartlägga brottsligheten inom sitt geografiska område och ta fram en lägesbild. Utifrån lägesbilden ska en åtgärdsplan tas fram. Kommunerna ska också ta visst ansvar för samordningen av det lokala brottsförebyggande arbetet och inrätta en samordningsfunktion.

### Plan- och bygglagen

Plan- och bygglagen (PBL) i Sverige syftar till att främja en långsiktigt hållbar utveckling av samhällen och miljöer. 

-	**Hållbar utveckling (1 kap. 1§):** Planläggning och byggande ska främja en samhällsutveckling med jämlika och goda sociala levnadsförhållanden och en god och långsiktigt hållbar livsmiljö för invånarna idag och för kommande generationer.

Läs mer här: [Plan och bygglagen (2010:900)](https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/plan-och-bygglag-2010900_sfs-2010-900/#K2)


## Kartläggnings- och fördjupningsfrågor 

Frågorna kan användas som stöd vid kartläggning och kvalitetssäkring av främjande och förebyggande verksamheter i kommunen. Med de kartläggande frågorna fångas inte enbart förekomst av en insats eller verksamhet utan även några grundläggande förutsättningar för ett kvalitativt arbete såsom finansiering, långsiktighet och uppföljning. De kartläggande frågorna syns under varje enskild verksamhet men kan även laddas ned här: [Kartläggning av Tryggt närsamhälle](/Kartläggning_community.xlsx) Denna kan ni sedan spara lokalt och arbeta vidare med, till exempel om ni vill jämföra de kartläggande frågorna över tid.

I de fördjupande frågorna kartläggs kvalitén i verksamheten eller insatsen på ett mer djupgående sätt. Frågorna kräver mer detaljerade svar och syftar till att identifiera eventuella utvecklings- och förbättringsområden såsom tillgänglighet, målgruppsanpassning, kompetensutveckling samt tillvägagångssätt för uppföljning. Klicka här för att hämta ner filen: [Dokumentation av fördjupande frågor](/Fördjupningsfrågor_community.docx). Denna kan ni sedan spara lokalt och arbeta vidare med. 


## Verksamheter och insatser: Ett tryggt närsamhälle

Nedan beskrivs verksamheter och insatser som kommuner enligt forskning, myndighetsrekommendationer eller lag kan/ska erbjuda för att stärka skyddsfaktorn *Ett tryggt närsamhälle.* Urvalet har förankrats med myndigheter, forskare, experter och kommuner, men är inte fullständigt och kan komma att revideras över tid.


### Kunskapsbaserat områdesarbete med lokal samverkan 

Kunskapsbaserat områdesarbete är en tvärsektoriell arbetsmetod som bygger på samarbete mellan bland annat invånare, kommunala verksamheter, lokala organisationer, näringsidkare och myndigheter. Metoden syftar till att förbättra och utveckla specifika geografiska områden genom en bred samhällsanalys.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Det finns samverkansformer för att bedriva områdesarbete mellan kommunala verksamheter, myndigheter, bostadsbolag, civilsamhällesorganisationer, näringsliv, hälso- och sjukvård samt invånare i området.  

- Det finns långsiktig finansiering för kommunens områdesarbete.

-	Kommunen har en lägesbild över brottsligheten inom sitt geografiska område samt en beslutad åtgärdsplan.

-	Kommunen har en samordningsfunktion för brottsförebyggande arbete.

-	Barn och ungdomar involveras i områdesarbetet.

_______________________________________________________________________________________________________________

**Lagstiftning**

*Lag (2023:196) om kommuners ansvar för brottsförebyggande arbete*

_______________________________________________________________________________________________________________

**Indikatorer**

- [Region Stockholm: Om livsvillkor, brott, narkotika samt otrygghet i Stockholms län](https://storymaps.arcgis.com/collections/8b89cbe67c354d2bb6f2215241f7f218/))

- [BRÅ: Indikatorer för kommuners lägesbild](https://bra.se/statistik/indikatorer-for-kommuners-lagesbild) 

_______________________________________________________________________________________________________________

**Läs mer om kunskapsbaserat områdesarbete**

- [Boverket: Samverkansmodeller för trygghetsfrämjande och brottsförebyggande arbete  ](https://www.boverket.se/sv/samhallsplanering/stadsutveckling/brottsforebyggande-och-trygghetsskapande-atgarder/metoder/samverkansmodeller/)

- [Socialstyrelsen: Effektiv samordning för ökad trygghet ](https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/barn-och-unga/unga-som-begar-brott/exempel-brottsforebyggande-metoder/effektiv-samordning-for-okad-trygghet-est/)

- [BRÅ:Arbeta brottsförebyggande ](hhttps://bra.se/forebygga-brott/arbeta-brottsforebyggande.html)

- [Boverket: Vägledning: Gåturer och Trygghetsvandring](https://www.boverket.se/sv/PBL-kunskapsbanken/teman/medborgardialog/metoder/gaturer-och-trygghetsvandringar/)

**------------------------------------------------------------------------------**

### Sociala perspektiv i samhällsplaneringsprocessen

Genom att i samhällsplanering inkludera sociala perspektiv och främja sociala värden så skapas förutsättningar för att fler människor kan och vill vistas i närsamhället. Det gör områden mer attraktiva även för företag att etablera sig i, vilket både skapar arbetstillfällen och ett utökat utbud lokalt som i sin tur leder till fler besökare. Att inkludera sociala värden handlar om att fler perspektiv, såsom exempelvis barnets perspektiv, äldres perspektiv och jämställdhetsperspektiv i större utsträckning blir synliga i den byggda miljön och i det offentliga rummet.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Kommunen arbetar aktivt med att integrera sociala perspektiv och värden i samhällsplaneringen. 

-	Det finns specifika riktlinjer eller policys för arbetet med att inkludera sociala perspektiv och värden i samhällsplaneringen.

-	Planeringen sker med kompetenser från olika verksamheter och sakkunniga i kommunen.

-	Barn och unga involveras i samhällsplaneringsprocessen.

-	Det görs kontinuerlig uppföljning för att bedöma hur väl sociala perspektiv och värden integreras i samhällsplaneringen.

_______________________________________________________________________________________________________________

**Lagstiftning**

- [Plan- och bygglag (2010:900)](https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/plan-och-bygglag-2010900_sfs-2010-900/#K2)

- [Hållbar socialtjänst – En ny socialtjänstlag SOU 2020:47)](https://www.regeringen.se/rattsliga-dokument/statens-offentliga-utredningar/2020/08/sou-202047/)

_______________________________________________________________________________________________________________

**Läs mer om sociala perpektiv och värden i samhällsplanering**

- [Healthy cities: Hälsofrämjande stadsplanering ](https://healthycities.se/wp-content/uploads/2013/07/Slutversion-h%C3%A4lsofr-stadsplan-2013-maj1.pdf)

- [Boverket: Barnkonventionen i fysisk planering och stadsutveckling ](https://www.boverket.se/sv/PBL-kunskapsbanken/teman/barnkonventionen/)

- [Boverket: Tillits- och trygghetsfrämjande planering ](https://www.boverket.se/sv/samhallsplanering/stadsutveckling/halsa-forst/social-inkludering/tillit-och-trygghet/)

- [SKR: Suicidprevention i fysisk miljö ](https://skr.se/skr/samhallsplaneringinfrastruktur/trafikinfrastruktur/trafikplaneringtrafiksakerhet/trafiksakerhet/suicidpreventionifysiskmiljo.28029.html)

- [Boverket: Att involvera barn i fysisk planering](https://www.boverket.se/sv/PBL-kunskapsbanken/teman/medborgardialog/metoder/skola_forskola/)


**------------------------------------------------------------------------------**

### Insatser för att stärka tillit

Social tillit, social sammanhållning, social kontroll och trygghet hänger ihop. Den sociala tilliten kan delas upp i institutionell tillit (förtroende för samhällsinstitutioner som myndigheter, kommunala verksamheter och sjukvård) samt mellanmänsklig tillit (förtroende mellan individer i ett område). Social tillit bidrar till en mer effektiv social kontroll eftersom invånare som känner sig trygga och delaktiga är mer benägna att följa samhällets normer och regler och agera för att upprätthålla dessa. I samhällen med större social tillit är människor mer benägna att ta hand om sin närmiljö, hjälpa till i kris och har lägre benägenhet att begå brott.

Nattvandring, tillgång till trygga mötesplatser, närvaro av samhällsservice i området samt dialoger med medborgare, inklusive barn och unga, bidrar till att utveckla den sociala tilliten och tryggheten i området.

_______________________________________________________________________________________________________________

**Kartläggning**

• Kommunen har en övergripande strategi och handlingsplan för tillitsskapande strategier, till exempel medborgardialoger.

• Kommunen samverkar med andra aktörer (skolor, fritidsföreningar, polis, väktare, hälso- och sjukvård) för att stärka den sociala tilliten.

• Det finns specifika forum eller metoder för att säkerställa att barn och ungas röster hörs.

• Kommunen arbetar aktivt med att implementera och stödja insatser för positiv social kontroll, såsom nattvandring 

• Uppföljning görs av vilka målgrupper som deltar i de tillitsskapande insatserna som medborgardialoger och nattvandringar.

_______________________________________________________________________________________________________________

**Indikatorer**

-	[SCB Medborgarundersökningen - Förtroende för kommunens politiker, andel (%)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__ME__ME0003__ME0003M/MedborgFortPol/)

-	[SCB Medborgarundersökningen - Invånarnas möjlighet till insyn och inflytande över kommunens beslut och verksamheter är bra, andel (%)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__ME__ME0003__ME0003N/MedborgOverInsyn/)

-	[SCB: Medborgarundersökningen - Möjlighet att delta aktivt i arbetet med att utveckla kommunen fungerar bra, andel (%)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__ME__ME0003__ME0003K/MedborgInflytande/)

-	[SCB: Medborgarundersökningen - Andel invånare som upplever att de fått ett mycket eller ganska bra bemötande vid den senaste kontakten med tjänsteperson vid kommunen – andel (%)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__ME__ME0003__ME0003K/MedborgBemotande/)

-	[Folkhälsokollen: Andelen män och kvinnor 16-84 år som uppger att de känner tillit till bostadsområdet](https://www.folkhalsokollen.se/folkhalsoomraden/)

_______________________________________________________________________________________________________________

**Läs mer om tillitsskapande insatser**

- [Healthy Cities: Tillitsfrämjande stadsplanering](https://www.healthycities.se/dokument/)

- [Internationellt centrum för lokal demokrati: Checklista för dialog med barn och unga](https://icld.se/publikationer/checklist-for-dialogue-with-children-and-young-people/)

-	[Kunskapsguiden: Involvera-barn-i-verksamhetsutveckling](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/involvera-barn-i-verksamhetsutveckling/)

-	[Boverket: Metoder och kanaler för att möta medborgare](hhttps://www.boverket.se/sv/PBL-kunskapsbanken/teman/medborgardialog/metoder/)

-	[SKR: Dialog med unga](https://skr.se/skr/demokratiledningstyrning/medborgardialogsamverkan/medborgardialog/dialogmedunga.82345.html)

-	[Socialstyrelsen: Nattvandring](https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/barn-och-unga/unga-som-begar-brott/exempel-brottsforebyggande-metoder/nattvandring/)

**------------------------------------------------------------------------------**

### Insatser för att främja tillgången till ett tryggt och hållbart boende

En trygg bostadsmiljö är en förutsättning för barn och ungas välmående. Rätten till bostad framgår av såväl svensk lagstiftning som internationell rätt. Barnkonventionens artikel nr 27 lyfter fram barns rätt till skälig levnadsstandard där bostaden är en väsentlig del. I artikeln framstår även konventionsstaternas ansvar att vid behov bistå föräldrarna med till exempel mat, kläder och bostad.
_______________________________________________________________________________________________________________

**Kartläggning**

- Hemlöshet och trångboddhet bland barnfamiljer kartläggs och följs upp. 

-	Det finns ett vräkningsförebyggande arbete för barnfamiljer.

-	Det finns bostadssociala insatser för att stödja hemlösa barnfamiljer till långsiktiga boendelösningar.

-	Det finns en etablerad samverkan med bostadsbolag kring bostadssociala lösningar för barnfamiljer som riskerar att hamna i - eller befinner sig i hemlöshet.

- Det finns en etablerad samverkan mellan socialtjänsten och samhällsplanering kring långsiktig bostadsförsörjning.

- Barn och unga görs delaktiga i bostadssociala frågor.


_______________________________________________________________________________________________________________

**Lagstiftning**

Lagen (2000:1383) om kommunernas bostadsförsörjningsansvar 

_______________________________________________________________________________________________________________

**Indikatorer**

-	[Kolada: Verkställda vräkningar/avhysningar som berör barn, antal barn/100 000 inv](https://www.kolada.se/verktyg/fri-sokning/)

-	[Kolada: Trångboddhet i flerbostadshus, enligt norm 2, andel (%)](https://www.kolada.se/verktyg/fri-sokning/)

-	[Boverkets bostadsmarknadsenkät: Bostadsmarknadsenkäten 2024](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fwww.lansstyrelsen.se%2Fdownload%2F18.1b1d393819324610c37484b0%2F1732515571104%2FBostadsmarknadsenk%25C3%25A4ten%25202024%2520-%2520Underlagstabell.xlsx&wdOrigin=BROWSELINK)

_______________________________________________________________________________________________________________

**Läs mer om insatser för att främja tillgången till ett tryggt och hållbart boende**

- [Regeringen: Nationell plan för barngarantin](https://www.regeringen.se/rattsliga-dokument/departementsserien-och-promemorior/2022/03/nationell-handlingsplan-for-att-implementera-den-europeiska-barngarantin/)

- [Länsstyrelsen Stockholm: Bostadsförsörjning](https://www.lansstyrelsen.se/stockholm/samhalle/planera-bygga-och-bo/bostadsforsorjning.html)

- [Boverket: Åtgärder för att motverka hemlöshet](https://boverket.se/sv/samhallsplanering/bostadsmarknad/olika-grupper/hemlosa/atgarder-for-att-motverka-hemloshet/)


**------------------------------------------------------------------------------**


### Trygga transportvägar 

Trygga och attraktiva cykel- samt gångvägar ger bättre förutsättningar för mer aktivitet och trivsel i närsamhället. För barn och unga är det en förutsättning för att de självständigt ska kunna ta sig mellan olika mål. Andelen barn som går eller cyklar har minskat de senaste åren och istället skjutsar allt fler föräldrar sina barn till skolan eller fritidsaktiviteter. Genom att skolor etableras i områden som från början inte var planerade att innehålla en skola saknas lämplig infrastruktur till platsen. Det fria skolvalet har även inneburit att barnen bor längre ifrån skolan än tidigare. Även föräldrarnas upplevelse av trafiksäkerheten påverkar om de låter barnen gå eller cykla på egen hand (SKR 2013). Detta är dock frågor som kan lösas med god planering.

_______________________________________________________________________________________________________________

**Kartläggning**

•	Det finns en plan för att säkerställa tillgång till och underhåll av cykel-, gång- och kollektivvägar.

•	Det finns en övergripande plan i kommunen för att säkerställa säkra vägar till och från skola/fritid.

•	Det finns belysning, tydlig skyltning och markerade övergångsställen.

•	Barn och unga inkluderas i planeringsprocessen. 

_______________________________________________________________________________________________________________

**Lagstiftning**

- [Plan- och bygglag (2010:900), Kap 2. 7§](https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/plan-och-bygglag-2010900_sfs-2010-900/#K2)

**Indikatorer**

-	[SCB: Medborgarundersökningen - Möjligheterna att enkelt använda kollektivtrafik till fritidsaktiviteter är bra, andel (%)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__ME__ME0003/)

_______________________________________________________________________________________________________________

**Läs mer om trygga transportvägar**

- [Boverket: Uppföljning av stöd till utemiljöer i vissa bostadsområden](https://www.boverket.se/sv/om-boverket/publicerat-av-boverket/publikationer/2019/uppfoljning-av-stod-till-utemiljoer-i-vissa-bostadsomraden/)

- [Boverket: Säkra och trygga vägar till förskola och skola](https://www.boverket.se/sv/samhallsplanering/arkitektur-och-gestaltad-livsmiljo/arbetssatt/skolors-miljo/larmiljoer-samhallsbygget/skolvagar/)

- [SKR: Trafiksäkerhet](https://skr.se/skr/samhallsplaneringinfrastruktur/trafikinfrastruktur/trafikplaneringtrafiksakerhet/trafiksakerhet.2982.html)

- [SKR: Kommunala trafik¬säkerhets¬program](https://skr.se/skr/tjanster/rapporterochskrifter/publikationer/kommunalatrafiksakerhetsprogram.65099.html)

**------------------------------------------------------------------------------**

### Socialt fältarbete
Socialt fältarbete för barn och unga handlar om att arbeta förebyggande genom att vara uppsökande och relationsskapande. Arbetet sker på platser och miljöer där barn och unga befinner sig och handlar om att skapa goda relationer för att kunna identifiera behov och erbjuda stöd och vägledning i barn och ungas vardag. Det kan handla om att ha kontakt med och ge stöd till föräldrar, ge råd om fritidsaktiviteter, eller stötta barn och unga direkt på plats. Genom att fältarbetarna är synliga och tillgängliga i närsamhället skapas en länk mellan invånarna och samhällets stödstrukturer. Förtroendet som byggs upp gör det lättare för individer att söka hjälp och stöd.

Samverkan med andra aktörer är en viktig uppgift där polis, skolor, andra delar av socialtjänsten, elevhälsan och fritidsgårdar är centrala aktörer tillsammans med civilsamhällets aktörer. Detta nätverkande är viktigt för att skapa en helhetsbild av barn och ungas situation och för att samordna samt hänvisa till insatser.

_______________________________________________________________________________________________________________

**Kartläggning**

- Kommunen arbetar med socialt fältarbete. 

- Det finns en överenskommelse och rutiner för samverkan mellan fältverksamheten och närliggande verksamhet som exempelvis socialtjänstens myndighetsutövning, öppenvård, skola, polis och fritidsverksamheter centralt.

- Det finns tydliga rutiner, riktlinjer och mål kring vad det sociala fältarbetet bör innehålla och leda till. 

- Det finns en långsiktig finansiering av fältverksamheten.

-	Arbetet dokumenteras och följs upp.  

-	Barn och ungdomars synpunkter och behov i inkluderas i utformningen av fältarbetet.

_______________________________________________________________________________________________________________

**Lagstiftning:**

Socialt fältarbete definieras inte i lagtexten men berörs delvis i förarbetena till socialtjänstlagen. Se avsnittet Uppsökande verksamhet och förebyggande arbete, 3 kap. 1 § SoL, 2 § första stycket, 2 § andra stycket.

_______________________________________________________________________________________________________________

**Läs mer om socialt fältarbete**

- [Socialstyrelsen: Socialt fältarbete med barn och unga](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2022-1-7731.pdf)

- [Kunskapsguiden: Socialt fältarbete med barn och unga](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/uppsokande-och-forebyggande-socialt-arbete/socialt-faltarbete-med-barn-och-unga/)

- [SKR: Motverka normbrytande beteende och förebyggande socialt fältarbete](https://skr.se/skr/samhallsplaneringinfrastruktur/trygghetsakerhet/brottsforebyggande/barnochungasombegarbrott/tidigaresandningar/motverkanormbrytandebeteendeochforebyggandesocialtfaltarbete.64373.html)

