---
title: "God föräldra-barnrelation"
title-block-banner: "#2D6B97"
title-block-banner-color: "#BBDBEC"
---

## Definition skyddsfaktor

En god föräldra-barnrelation har visat sig främja en god fysisk, psykisk, kognitiv och social utveckling och är en av de viktigaste skyddsfaktorerna för barn och unga. Det innebär att en god relation mellan föräldrar och barn minskar de negativa konsekvenserna av olika påfrestningar och riskbeteenden hos barnen och skyddet består långt upp i åldrarna.

Byggstenar för en god relation är värme, närvaro, bekräftelse och tydliga ramar från föräldrarnas sida. Ett gott samspel främjas enligt forskningen genom att föräldrarna ger tillräckligt med positiv uppmärksamhet och att denna överväger den negativa uppmärksamheten i form av tjat och tillsägelser. En god relation är också en förutsättning för att kunna sätta gränser som barnet respekterar.


## Underlag för verksamhetskartläggning och analys av *en god föräldra-barnrelation*

I texten avses både *föräldrar och vårdnadshavare*, men enbart begreppet föräldrar kommer att skrivas ut om texten inte är ett direkt referat från myndighet eller dylikt där andra begrepp använts.


### Konventionen om barnets rättigheter

Artikel 5 och 18 handlar om att det är föräldrarna som tillsammans har huvudansvaret för barnets uppfostran och utveckling. Föräldrarna ska hjälpa barnet så att det får sina rättigheter tillgodosedda. För att garantera och främja de rättigheter som anges i konventionen ska konventionsstaterna ge lämpligt stöd till föräldrar och vårdnadshavare då de fullgör sitt ansvar för barnets uppfostran och säkerställa utvecklingen av institutioner, inrättningar och tjänster för omvårdnad av barn.


### Nationell strategi för ett stärkt föräldraskapsstöd

Regeringen tog 2018 beslut om en nationell strategi för ett stärkt föräldraskapsstöd. Målet är att alla föräldrar ska erbjudas föräldraskapsstöd under hela barnets uppväxt för att barnets hälsa och utveckling ska främjas. Enligt den nationella strategin för ett stärkt föräldraskapsstöd är föräldraskapsstöd definierat som olika insatser, aktiviteter och verksamheter riktade till föräldrar som stärker föräldraförmågan och relationen mellan förälder och barn. Strategin betonar att stöd ska erbjudas alla föräldrar, oberoende av problem och risk. Grunden är det universella stödet som ska stärka hälsan och förebygga ohälsa hos alla barn. Riktat stöd till riskgrupper samt individuellt stöd till familjer med konstaterade problem ska komplettera det generella stödet. Föräldraskapsstöd bör erbjudas på flera olika arenor för att nå alla grupper av föräldrar.

I strategin finns även skrivningar som tydliggör vikten av att föräldraskapsstödet bidrar till ett mer jämställt föräldraskap, till exempel genom att möta föräldrars behov av stöd i sin relation till varandra och i sina ambitioner att leva jämställt. Ett jämställt föräldraskap, där båda föräldrarna deltar och gemensamt utövar omsorgen om barnet, gynnar barns hälsa och utveckling. Vidare behöver föräldraskapsstödet utmana begränsande och destruktiva föreställningar om kön och främja alla föräldrars delaktighet i frågor som traditionellt har betraktats som antingen mammors eller pappors ansvarsområde. 

Läs mer här: [Nationell strategi för ett stärkt föräldraskapsstöd](https://www.mfof.se/download/18.1af131d916e45020f6b3a437/1574348799172/En nationell strategi f%C3%B6r ett st%C3%A4rkt f%C3%B6r%C3%A4ldraskapsst%C3%B6d WEBB (1).pdf)


## Kartläggnings- och fördjupningsfrågor

Frågorna kan användas som stöd vid kartläggning och kvalitetssäkring av främjande och förebyggande verksamheter i kommunen. Med de kartläggande frågorna fångas inte enbart förekomst av en insats eller verksamhet utan även några grundläggande förutsättningar för ett kvalitativt arbete såsom finansiering, långsiktighet och uppföljning. De kartläggande frågorna syns under varje enskild verksamhet men kan även laddas ned här: [Kartläggning av Föräldra-Barnrelation](/Kartläggning_fldr.xlsx) Denna kan ni sedan spara lokalt och arbeta vidare med, till exempel om ni vill jämföra de kartläggande frågorna över tid.

I de fördjupande frågorna kartläggs kvalitén i verksamheten eller insatsen på ett mer djupgående sätt. Frågorna kräver mer detaljerade svar och syftar till att identifiera eventuella utvecklings- och förbättringsområden såsom tillgänglighet, målgruppsanpassning, kompetensutveckling samt tillvägagångssätt för uppföljning. Klicka här för att hämta ner filen: [Dokumentation av fördjupande frågor](/Fördjupningsfrågor_fldr.docx). Denna kan ni sedan spara lokalt och arbeta vidare med. 


## Verksamheter och insatser: En god föräldra-barnrelation

Nedan beskrivs verksamheter och insatser som kommuner enligt forskning, myndighetsrekommendationer eller lag bör erbjuda och som stärker skyddsfaktorn *en god föräldra-barnrelation*. Urvalet har förankrats med myndigheter, forskare, experter och kommuner men är inte fullständigt och kan komma att revideras över tid.

### Tidiga samordnade insatser runt barn och ungdomar

En strukturerad samverkan på flera nivåer i den kommunala organisationen är en förutsättning för att samverkan runt enskilda barn och ungdomar ute i verksamheterna ska fungera. En strukturerad samverkan är också viktig för att kännedom om verksamheter och insatser ska öka och underlätta hänvisning och information till målgruppen. Vilka aktörer som behöver samverka kan skilja sig åt men förutsättningarna förbättras om en bred samverkan med till exempel förskola/skola, socialtjänst, hälso-och sjukvård (BMM, BVC), elevhälsa, kultur- och fritidsverksamhet, civilsamhälle samt polis finns på plats

När aktörer och verksamheter som erbjuder olika former av föräldraskapsstöd samverkar med varandra så ökar möjligheterna att identifiera och erbjuda relevant stöd i tid. Kunskap från flera verksamheter ger en bättre helhetsbild av barnets eller ungdomens behov av stöd och lämpliga insatser där även föräldrarnas situation och behov av stöd är en viktig del.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Det finns en skriftlig överenskommelse rörande samordnade insatser runt barn och ungdomar där föräldraskapsstöd ingår.

-	Det finns mål och strategier för arbetet med samordnade insatser runt barn och ungdomar.

-	Det finns långsiktig finansiering för samordnade insatser runt barn och ungdomar. 

-	Det finns en samordnare för föräldraskapsstöd.

- Barn, ungdomar och föräldrar involveras i utformningen av insatserna.

- Det görs uppföljning av vilka målgrupper som nås genom de samordnade insatserna.

- Det görs uppföljning av arbetets resultat för föräldrar, barn och ungdomar.

_______________________________________________________________________________________________________________

**Läs mer om tidiga och samordnade insatser runt barn och ungdomar**

-   [SKR: Kronobarnsmodellen](https://skr.se/skr/halsasjukvard/utvecklingavverksamhet/naravard/nyaarbetssatt/samordningutifranbarnetsfokus.73797.html)

-   [Kunskapsguiden: Om tidiga och samordnade insatser (TSI)](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/)

-   [TSI-boken - Stöd i arbetet med tidiga och samordnade insatser för barn och unga](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2023-10-8779.pdf)

-   [Kunskapsguiden: Skottlandsmodellen](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/skottlandsmodellen/)

-   [Backa barnet](https://www.backabarnet.se/)

-   [Malmö stad: Communities that care (CTC)](https://malmo.se/Communities-That-Care-CTC.html)

-   [Socialstyrelsen: SSPF (skola, socialtjänst, polis, fritid)](https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/barn-och-unga/unga-som-begar-brott/exempel-brottsforebyggande-metoder/sspf-skola-socialtjanst-polis-fritid/)

**------------------------------------------------------------------------------**

### Utökat hembesöksprogram

Syftet med utökat hembesöksprogram är att stärka familjens tillit till sin egen förmåga och delaktighet i samhället samt att tidigt upptäcka familjer med behov av extra stöd - och erbjuda det. I ursprungsversionen av programmet sker hembesöken i samverkan mellan barnhälsovård och socialtjänsten, men även andra aktörer har med tiden inkluderats. I modellen ingår sex hembesök när barnet är mellan 0-15 månader gammalt.

_______________________________________________________________________________________________________________

**Kartläggning**

-  Utökat hembesöksprogram erbjuds i vår kommun.

-  Det finns mål och strategier för arbetet med utökat hembesöksprogram.

-  Det finns långsiktig finansiering för arbetet  med utökat hembesöksprogram.

-  Det görs uppföljning av vilka som deltar i det utökade hembesöksprogrammet. 

-  Det görs uppföljning av arbetets resultat för föräldrar och barn. 

_______________________________________________________________________________________________________________

**Läs mer om hembesöksprogram**

-   [Karolinska institutet: Vägledning Rinkeby hembesöksprogram](https://ki.se/media/77454/download)

-   [Karolinska institutet. Utvärderingsrapport 2015. Utökat barnhälsovårdsprogram för förstagångsföräldrar - samverkan mellan Rinkeby BVC och föräldrarådgivare inom Rinkeby-Kista socialtjänst. ](http://dok.slso.sll.se/CES/FHG/Rapport-FHM-utokat-barnhalsovardsprogram.pdf)

-   [Göteborgsregionen: Betydelser och effekter av utökade hembesök i Göteborg](https://goteborgsregionen.se/kunskapsbank/betydelserocheffekteravutokadehembesokigoteborg.5.28065c9318a25ff30f8d89a.html)


**------------------------------------------------------------------------------**

### Familjecentral

Familjecentraler i Sverige arbetar i huvudsak med barn 0–6 år men riktar sig även till blivande föräldrar och andra viktiga vuxna kring barnet. År 2023 fanns det omkring 180 familjecentraler i Sverige. Enligt definition samlokaliserar familjecentralen fyra verksamheter – barnmorskemottagning (BMM), barnavårdscentral (BVC), öppen förskola och förebyggande socialtjänst. 

Föreningen för familjecentralers främjande (FFFF) är en nationell förening som arbetar med utveckling och stöd till befintliga familjecentraler i landet. Målet med familjecentralers verksamhet är enligt FFFF att främja en god och jämlik hälsa hos blivande föräldrar, barn, föräldrar och andra viktiga vuxna runt barnet.

_______________________________________________________________________________________________________________

**Kartläggning**

- Det finns en eller flera familjecentraler i kommunen.

- Det finns mål och strategier för arbetet med familjecentraler.

- Det finns långsiktig finansiering av familjecentraler.

-	Det görs uppföljning av vilka som besöker familjecentralen.

-	Barn och föräldrar involveras i utformningen av verksamheten.

- Det görs uppföljning av familjecentralens resultat för barn och föräldrar.

_______________________________________________________________________________________________________________

**Indikatorer**

-   [Kolada: Antal öppna förskolor, samt varav på familjecentral, i relation till antal barn 0-6 år per län och kommun](https://www.kolada.se/verktyg/fri-sokning/?kpis=148817&years=30200,30199,30198&municipals=82304&rows=municipal,kpi&visualization=bar-chart)

_______________________________________________________________________________________________________________

**Läs mer om familjecentraler**

-   [Föreningen för familjecentralers främjande (FFFF): Vad är en familjecentral?](https://familjecentraler.se/foreningen/vad-ar-en-familjecentral/)

-   [Folkhälsomyndigheten: Familjecentralers betydelse för familjers hälsa och välmående – Resultat från en kartläggande litteraturöversikt](https://www.folkhalsomyndigheten.se/publikationer-och-material/publikationsarkiv/f/familjecentralers-betydelse-for-familjers-halsa-och-valmaende/)

-   [Socialstyrelsen och Folkhälsomyndigheten: Familjecentraler och familjecentralsliknande verksamheter - Kartläggning, analys och förslag](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2023-9-8728.pdf)



**------------------------------------------------------------------------------**

### Öppen förskola

Öppen förskola är en pedagogisk verksamhet för barn samt medföljande förälder, dagbarnvårdare eller annan vuxen. Den fungerar som en mötesplats där barn kan leka och delta i olika aktiviteter under pedagogisk ledning. Samtidigt kan föräldrarna träffa andra vuxna, utbyta erfarenheter och få stöd i sitt föräldraskap. Öppna förskolan är en verksamhet med låga trösklar och därför även en viktig arena för informationsinsatser för att öka deltagandet i förskolan för barn med utländsk bakgrund samt bidra till integration och språkutveckling.

Öppna förskolor finansieras oftast av kommunen och kan vara samlokaliserad i en familjecentral. Verksamheten är i allmänhet avgiftsfri.

_______________________________________________________________________________________________________________

**Kartläggning**

- Det finns en eller flera öppna förskolor i kommunen.

- Det finns mål och strategier för arbetet med öppen förskola.

- Det finns långsiktig finansiering av den öppna förskolan.

- Det görs kontinuerlig uppföljning av vilka som besöker den öppna förskolan.

-	Besökare inkluderas i utformning av innehållet i verksamheten. 

_______________________________________________________________________________________________________________

**Lagstiftning**

*Skollagen 25 kap. 3 §*

Den öppna förskolan ska erbjuda barn en pedagogisk verksamhet i samarbete med de till barnen medföljande vuxna, samtidigt som de vuxna ges möjlighet till social gemenskap.

_______________________________________________________________________________________________________________

**Indikatorer**

-   [Kolada: Antal öppna förskolor, samt varav på familjecentral, i relation till antal barn 0-6 år per län och kommun](https://www.kolada.se/verktyg/fri-sokning/?kpis=148817&years=30200,30199,30198&municipals=82304&rows=municipal,kpi&visualization=bar-chart)

-	[Kolada: Öppen förskola, andel (%) heltidstjänster med pedagogisk högskoleutbildning](https://www.kolada.se/verktyg/fri-sokning/?kpis=148822&years=30200,30199,30198&municipals=82304&rows=municipal,kpi&visualization=bar-chart)

-	[Kolada: Öppen förskola, öppethållande minst 16 tim/vecka](https://www.kolada.se/verktyg/fri-sokning/?kpis=148816&years=30200,30199,30198&municipals=82304&rows=municipal,kpi&visualization=bar-chart)


_______________________________________________________________________________________________________________

**Läs mer om öppen förskola**

-   [Myndigheten för familjerätt och föräldraskapsstöd: Öppen förskola](https://www.mfof.se/foraldraskapsstod/arenor-for-foraldraskapsstod/oppen-forskola.html)

-   [Skolverket; Allmänna råd för öppen förskola](https://www.skolverket.se/download/18.6bfaca41169863e6a6538f8/1553956773578/pdf607.pdf)

-   [SKR: Öppen förskola – tillsammans för jobb och integration](https://skr.se/skr/skolakulturfritid/forskolagrundochgymnasieskolakomvux/oppenforskolaforsprakochintegration.46558.html)

**------------------------------------------------------------------------------**

### Samverkan mellan förskola/skola och föräldrar

Förskola, skola och fritids är verksamheter som möter majoriteten av alla föräldrar och barn under större delen av barnens uppväxt. Både förskola och skola är därför viktiga arenor för samverkan med och stöd till föräldrar. Enligt Skolverket kan skolan erbjuda information och stödjande samtal från elevhälsan samt mer kontinuerliga avstämningar mellan förskola/fritids och förälder vid hämtningar. Förskola och skola kan även bjuda in andra föräldrastödjande verksamheter vid föräldramöten. Även föräldraskapsstödsprogram kan erbjudas via förskola och skola och utföras av utbildad personal från förskolan, skolan, elevhälsan, socialtjänsten eller liknande.

I skolans systematiska kvalitetsarbete ingår att löpande utveckla och utvärdera samverkan med föräldrar och vårdnadshavare för att säkerställa att man når ut till alla.

_______________________________________________________________________________________________________________

**Kartläggning**

- Det finns en kommunövergripande plan för förskolans, skolans och fritidshemmens samverkan med föräldrar.

-	Kommunen erbjuder personalen kunskapshöjande insatser om föräldraskapsstöd och föräldrasamverkan.

- Respektive förskola/skola har en gemensam strategi för att möjliggöra för hem och föräldrar att bli delaktiga i frågor som rör elevens skolgång.

- Respektive förskola/skola har gemensamma förhållningssätt i kontakter med föräldrar och hemmen.

- Stöd i föräldraskapet erbjuds via förskolor/skolor i kommunen. 

- Det görs kontinuerlig uppföljning av hur föräldrar uppfattar samverkan med förskola/skola. 

_______________________________________________________________________________________________________________

**Lagstiftning**

*Skollagen 1 kap. 4 §*

Utbildningen syftar också till att i samarbete med hemmen främja barns och elevers allsidiga personliga utveckling till aktiva, kreativa, kompetenta och ansvarskännande individer och medborgare.

_______________________________________________________________________________________________________________

**Läs mer om samverkan mellan förskola/skola och föräldrar**

-   [Skolverket: Föräldraskapsstöd kan främja lärande och hälsa](https://www.skolverket.se/skolutveckling/forskning-och-utvarderingar/artiklar-om-forskning/foraldraskapsstod-kan-framja-larande-och-halsa)

-   [Skolverket: Utveckla skolans samverkan med hem och vårdnadshavare](https://www.skolverket.se/skolutveckling/inspiration-och-stod-i-arbetet/stod-i-arbetet/utveckla-skolans-samverkan-med--hem-och-vardnadshavare)

-   [Skolverket: Checklista för att utveckla er skolas samverkan med hem och vårdnadshavare ](https://www.skolverket.se/download/18.3cf0d66d187913b54fe15f6/1684141494320/checklista-utveckla-samverkan-1.pdf)

-   [Skolverket: Skolan och hemmet - exempel och forskning om lärares samarbete med elevernas vårdnadshavare](https://www.skolverket.se/publikationsserier/stodmaterial/2015/skolan-och-hemmet)

-   [Specialpedagogiska skolmyndigheten (SPSM): Samarbete och kommunikation för elevernas bästa](https://www.spsm.se/systematik-for-tidiga-stodinsatser/del-4---att-prova-och-omprova-tillsammans/samarbete-och-kommunikation-for-elevernas-basta/)

**------------------------------------------------------------------------------**

### Föräldragrupp MHV/BHV

Föräldragrupper inom mödrahälsovården (MHV) och barnhälsovården (BHV) syftar till att stärka föräldrar, främja goda uppväxtvillkor samt tidigt fånga upp föräldrar och barn i behov av stöd. I barnmorskemottagningarnas basprogram ingår att erbjuda generellt föräldraskapsstöd och inom barnhälsovården är föräldragrupper en grundläggande arbetsmetod. Samverkan inom och mellan regionens och kommunernas verksamheter för blivande föräldrar och föräldrar ingår också i uppdragen.

I den nationella strategin för ett stärkt föräldraskapsstöd tydliggörs vikten av att föräldraskapsstödet bidrar till ett mer jämställt föräldraskap, till exempel genom att möta föräldrars behov av stöd i sin relation till varandra och i sina ambitioner att leva jämställt. Föräldraskapsstödet ska även utmana begränsande och destruktiva föreställningar om kön och främja alla föräldrars delaktighet i frågor som traditionellt har betraktats som antingen mammors eller pappors ansvarsområde. 

_______________________________________________________________________________________________________________

**Kartläggning**

- Föräldrar i kommunen erbjuds föräldragrupp via MHV respektive BHV.

- Det finns samverkan mellan kommun och region gällande föräldragrupperna. 

- Det finns mål och strategier för arbetet med föräldragrupperna.

- Det finns långsiktig finansiering för arbetet med föräldragrupperna.

- Föräldrars synpunkter involveras i utformningen av grupperna.

- Det görs uppföljning av vilka som deltar i föräldragrupper på MHV respektive BHV.

- Det görs uppföljning av vilka resultat som grupperna får för barn och föräldrar.


_______________________________________________________________________________________________________________

**Indikatorer**

-   [Folkhälsokollen: Deltagande i föräldraskapsstöd under graviditet](https://www.folkhalsokollen.se/webbverktyg/?id=260266)

-   [Kolada: Föräldrapenningdagar som tas ut av män respektive kvinnor, andel av antal dagar (%)](https://www.kolada.se/verktyg/fri-sokning/?kpis=60615&years=30199,30198,30197,30196,30195,30194,30193,30192,30191&municipals=2328,16536&rows=municipal,kpi&visualization=line-chart&scale=blue&interval=10-80-10)


_______________________________________________________________________________________________________________

**Läs mer om föräldragrupper MVC/BVC**

-   [Rikshandboken Barnhälsovård: Föräldraskapsstöd i grupp - översikt](https://www.rikshandboken-bhv.se/metoder--riktlinjer/foraldraskapsstod-i-grupp/)

-   [Socialstyrelsen: Graviditet, förlossning och tiden efter. ](www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/kunskapsstod/2022-12-8287.pdf)

-   [Linköpings universitet: Föräldragrupper inom mödra- och barnhälsovård - Forskning, tillämpning och metoder om ledarskap för välfungerande grupper](https://www.diva-portal.org/smash/get/diva2:1599399/FULLTEXT01.pdf)

-   [MFOF: Lilla ABC](https://mfof.se/foraldraskapsstod/program-och-metoder-for-foraldraskapsstod---soksida/fss-program/2022-10-25-lilla-abc.html)

**------------------------------------------------------------------------------**

### Universella föräldrastödsprogram

Den nationella strategin för ett stärkt föräldraskapsstöd betonar att stöd ska erbjudas alla föräldrar, oberoende av problem och risk. Grunden är det universella stödet som ska stärka hälsan och förebygga ohälsa hos alla barn. Strategin betonar även att föräldraskapsstödet behöver bidra till ett mer jämställt föräldraskap, till exempel genom att möta föräldrars behov av stöd i sin relation till varandra och i sina ambitioner att leva jämställt. Föräldraskapsstödet ska även utmana begränsande och destruktiva föreställningar om kön och främja alla föräldrars delaktighet i frågor som traditionellt har betraktats som antingen mammors eller pappors ansvarsområde. 

Syftet med universella föräldraskapsstödsprogram är dels att ge alla föräldrar stöd i föräldraskapet och främja en god utveckling hos barn, dels att fånga upp och hänvisa vidare föräldrar med behov av mer stöd. Eftersom universellt stöd ofta erbjuds på öppna arenor kan det underlätta för familjer med lägre samhällstillit att söka stöd där.

Studier visar att satsningar på föräldraskapsstödsprogram är hälsoekonomiskt lönsamt och kostnadsbesparande, även om effekten endast skulle kvarstå i ett år. [Källa: MFoF](mfof.se)

_______________________________________________________________________________________________________________

**Kartläggning**

- Det erbjuds universella föräldraskapsstödsprogram i kommunen, exempelvis:

  - [Alla Barn i Centrum 0-2, Lilla ABC, Alla Barn i Centrum 3-12, Alla Barn i Centrum Tonår) ](https://www.ipsykologi.se/projekt/komet-abc)
  - [COPE](https://svenskacope.se/)
  - [Connect](https://www.humana.se/individ-och-familj/metoder-och-utbildning/connect/)
  - [Vägledande samspel](https://icdp.se/stiftelsen-icdp/om-vagledande-samspel/)
  - [Triple P](https://triplep.uppsala.se/)

- Det finns mål och strategier för arbetet med universella föräldraskapsstödsprogram.

- Det finns långsiktig finansiering för universella föräldraskapsstödsprogram.

- Det finns struktur för arbetet (exempelvis återkommande utbildning av gruppledare, samordnare och kompetensutveckling).

-	Föräldrars synpunkter involveras i föräldraskapsstödets utformning.

- Det görs återkommande uppföljning av vilka som deltar i universella föräldraskapsstödsprogram.

- Det görs uppföljning av vilka resultat som programmen får för barn och föräldrar.

_______________________________________________________________________________________________________________

**Indikatorer**

 - [Kolada: Tillfälliga föräldrapenningdagar (VAB) som tas ut av män respektive kvinnor, andel av antal dagar (%)](https://www.kolada.se/verktyg/fri-sokning/?kpis=60615,60616&years=30199,30198,30197,30196,30195,30194,30193,30192,30191&municipals=2328,16536&rows=municipal,kpi&visualization=line-chart&scale=blue&interval=10-80-10)
 
_______________________________________________________________________________________________________________

**Läs mer om universella föräldrastödsprogram**

- [MFOF: En nationell översikt av program och metoder för föräldraskapsstöd](https://mfof.se/foraldraskapsstod/program-och-metoder.html)

-   [MFOF: Effekter av föräldraskapsstöd](https://mfof.se/foraldraskapsstod/effekter-av-foraldraskapsstod.html)

-   [Karolinska Institutet: Beforskade program på Ipsykologi.se](https://www.ipsykologi.se/projekt/komet-abc)

-   [Karolinska Institutet: Effektutvärdering ABC föräldraträffar](https://bmcpublichealth.biomedcentral.com/articles/10.1186/1471-2458-14-1083)

**------------------------------------------------------------------------------**

### Riktade föräldrastödsprogram

Enligt den nationella strategin för ett stärkt föräldraskapsstöd ska riktat stöd till riskgrupper samt individuellt stöd till familjer med konstaterade problem komplettera det universella stödet. Föräldraskapsstöd bör erbjudas på flera olika arenor för att nå alla grupper av föräldrar. Strategin betonar även att föräldraskapsstödet behöver bidra till ett mer jämställt föräldraskap, till exempel genom att möta föräldrars behov av stöd i sin relation till varandra och i sina ambitioner att leva jämställt. Föräldraskapsstödet ska även utmana begränsande och destruktiva föreställningar om kön och främja alla föräldrars delaktighet i frågor som traditionellt har betraktats som antingen mammors eller pappors ansvarsområde. 

Syftet med riktade föräldrastödsprogram är att vända en negativ utveckling med bråk och konflikter i familjen eller normbrytande beteende hos barnet då detta utgör en risk för en fortsatt problematisk utveckling. Indikerat stöd ges till familjer med större identifierade problem eller tydliga symtom på ohälsa.

_______________________________________________________________________________________________________________

**Kartläggning**

- Det erbjuds riktade föräldraskapsstödsprogram i vår kommun, exempelvis:

  - [KOMET 3-12, KOMET Tonår, iKOMET ](https://www.ipsykologi.se/projekt/komet-abc)
  - [Tryggare barn ](https://magelungen.com/akademi/12349-2/)
  - [Föräldraskap i Sverige](https://www.foraldraskapisverige.se/)
  - [FFT](hhttps://www.stiftelsenfftsverige.se/)

- Det finns mål/strategier för arbetet med riktade föräldraskapsstödsprogram.

- Det finns långsiktig finansiering för riktade föräldraskapsstödsprogram.

- Det finns struktur för arbetet (exempelvis återkommande utbildning av gruppledare, samordnare och kompetensutveckling).

-	Föräldrars synpunkter involveras i föräldraskapsstödets utformning.

- Det görs återkommande uppföljning av vilka som deltar i riktade föräldraskapsstödsprogram.

- Det görs uppföljning av vilket resultat som programmen får för barn och föräldrar.

_______________________________________________________________________________________________________________

**Läs mer om riktade föräldrastödsprogram**

-   [Karolinska Institutet: Forskning på föräldraskapsstödsprogram](https://www.ipsykologi.se/forskning)

-   [MFOF: Översikt av program och metoder för föräldraskapsstöd](https://mfof.se/foraldraskapsstod/program-och-metoder-for-foraldraskapsstod---soksida.html#query/*)

-   [Socialstyrelsen: Insatser för att motverka fortsatt normbrytande beteende och återfall i brott](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/kunskapsstod/2021-11-7626.pdf)

-   [Socialstyrelsen: Effekter av föräldrastödsprogram](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2014-11-12.pdf)

-   [Kunskapsguiden: Exempel på föräldrastöd till utrikesfödda föräldrar](https://kunskapsguiden.se/omraden-och-teman/arbetsmetoder-och-perspektiv/interkulturellt-perspektiv/forebyggande-arbete-stod-och-insatser/)

**------------------------------------------------------------------------------**

### Föräldraföreläsningar

Föräldraföreläsningar kan ges på olika teman och arenor och är ett verktyg för att nå ut med kunskap och stöd till fler föräldrar. Att erbjuda verksamheter och insatser med låga trösklar är viktigt för att göra stödet mer tillgängligt och även nå målgrupper med lägre samhällstillit. Syftet kan också vara att bidra till ökad kännedom om kommunens övriga föräldraskapsstöd och skapa kontaktytor mellan föräldrar men även mellan föräldrar och samhälle.

_______________________________________________________________________________________________________________

**Kartläggning**

- Det erbjuds regelbundet föräldraföreläsningar till föräldrar i kommunen.

- Det finns mål och strategier för arbetet med föräldraföreläsningar.

-	Föräldrar samt barn och unga involveras i föräldraföreläsningarnas innehåll och utformning.

- Det finns långsiktig finansiering av föräldraföreläsningar.

- Det görs uppföljning av vilka som tar del av föräldraföreläsningarna.

_______________________________________________________________________________________________________________

**Läs mer om föräldraföreläsningar**

-   [Inspirationsföreläsning gör nyblivna föräldrar tryggare](https://www.forskning.se/2020/08/25/inspirationsforelasning-gor-nyblivna-foraldrar-tryggare/)

**------------------------------------------------------------------------------**

### Familjerådgivning

Familjerådgivning består av samtal med syfte att bearbeta samlevnadskonflikter i parförhållanden och familjer. På universell nivå kan familjerådgivningen genom sitt utåtriktade uppdrag ge breda folkbildande insatser om relationer och relationsproblem på arenor som exempelvis mödravårdens, barnhälsovårdens och familjecentralens föräldrautbildningar. På selektiv nivå kan familjerådgivning istället rikta insatser mot särskilda grupper som identifierats av kommunen.

_______________________________________________________________________________________________________________

**Kartläggning**

- Kommunen erbjuder familjerådgivning.

- Det finns mål och strategier för arbetet med familjerådgivning.

- Barn ges möjlighet att komma till tals i samband familjerådgivning.

- Standardiserade modeller, metoder, verktyg eller bedömningsinstrument används under samtalen.

- Det görs uppföljning av vilka som deltar i familjerådgivningen. 

-	Det görs uppföljning av vilket resultat familjerådgivningen får för barn och föräldrar.

_______________________________________________________________________________________________________________

**Lagstiftning** 

*Socialtjänstlagen 5 kap. 3 §*

Kommunen ska sörja för att familjerådgivning genom kommunens försorg eller annars genom lämplig yrkesmässig rådgivare kan erbjudas dem som begär det.

Med familjerådgivning avses i denna lag en verksamhet som består i samtal med syfte att bearbeta samlevnadskonflikter i parförhållanden och familjer.

_______________________________________________________________________________________________________________

**Indikatorer**

-   [SCB: Familjerådgivning: Teknisk rapport - En beskrivning av genomförande och metoder](https://mfof.se/download/18.7fecc00c1884c539cd42e4b1/1686116419181/Statistik%20familjer%C3%A5dgivning%202022_Teknisk%20rapport.pdf)

_______________________________________________________________________________________________________________

**Läs mer om familjerådgivning**

-   [MFOF: Barnrättsbaserad familjerådgivning](https://mfof.se/familjeradgivning.html)

-   [MFoF:s vägledande material för arbetet med familjerådgivning i Sveriges kommuner](https://mfof.se/download/18.70103d0c17f2a79704e4486/1645793221507/V%C3%A4gledning%20familjer%C3%A5dgivning%20februari%202022.pdf)

**------------------------------------------------------------------------------**

### Samarbetssamtal

Samarbetssamtal erbjuds med syftet att få föräldrar att nå enighet i frågor som gäller vårdnad, boende och umgänge.

**Kartläggning**

- Kommunen erbjuder samarbetssamtal.

- Det finns mål och strategier för arbetet med samarbetssamtal.

- Barn ges möjlighet att komma till tals i samband samarbetssamtalen.

- Standardiserade modeller, metoder, verktyg eller bedömningsinstrument används under samtalen.

- Det görs uppföljning av vilka som deltar i samarbetssamtal.

- Det görs uppföljning av vilket resultat samarbetssamtalen får för barn och föräldrar. 

_______________________________________________________________________________________________________________

**Lagstiftning**

Enligt socialtjänstlagen (2001:453), (5 kap. 3 §), ska kommunen sörja för att föräldrar kan erbjudas samtal under sakkunnig ledning i syfte att nå enighet i frågor som gäller vårdnad, boende och umgänge (samarbetssamtal). I föräldrabalken infördes samtidigt en möjlighet för rätten att besluta om samarbetssamtal när en process om vårdnad och umgänge inletts.

_______________________________________________________________________________________________________________

**Läs mer om samarbetssamtal:**

-   [Socialstyrelsen: Interventioner för att förebygga och hantera föräldrars konflikter och tvister kring vårdnad, boende och umgänge](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2011-6-32.pdf)

-   [MFOF: Vad är samarbetssamtal?](https://mfof.se/vardnad-boende-och-umgange/information-for-foraldrar/vad-ar-samarbetssamtal.html)

-   [MFOF: Forskning om samarbetssamtal och medling](https://www.mfof.se/download/18.78bdeb3e17e98c36ecf5a5f3/1643878965346/Forskning%20om%20samarbetssamtal%20och%20medling.pdf)

**------------------------------------------------------------------------------**

### Skolsociala team

Skolsociala team är ett tvärprofessionellt arbetssätt där socialtjänst och skola samverkar för att öka trygghet, skolnärvaro och måluppfyllelse samt ge elever med en ogynnsam utveckling stöd i ett tidigt skede. Skolsociala team kan till exempel erbjuda stödinsatser till föräldrar och underlätta kommunikation och samarbete mellan föräldrar och övriga aktörer som finns runt den enskilda eleven som till exempel hälso- och sjukvård och fritidssektor.

_______________________________________________________________________________________________________________

**Kartläggning**

- Det finns skolsociala team i kommunen.

-	Det finns mål och strategier för arbetet med skolsociala team

-	Det finns en långsiktig finansiering för arbetet med skolsociala team.

-	Barn och föräldrar inkluderas i utformningen av de skolsociala teamen.

-	Det görs uppföljning av vilka målgrupper som får insatser via skolsociala team.

-	Det görs uppföljning av vilket resultat skolsociala team får för barn och föräldrar.

_______________________________________________________________________________________________________________

**Lagstiftning:**

Skolans elevhälsoarbete stärktes i skollagen 2023. Det innebär bland annat att elevhälsan vid behov ska samverka med hälso- och sjukvården och socialtjänsten

_______________________________________________________________________________________________________________

**Läs mer om skolsociala team**

- [Skolverket: Starta och arbeta med skolsociala team](https://www.skolverket.se/skolutveckling/leda-och-organisera-skolan/ge-extra-stod-till-elever/starta-och-arbeta-med-skolsociala-team)

-   [Marie Cederschiöld högskola: Att arbeta med skolsociala team - Utvärdering av innehåll och arbetssätt i Stockholm stad](https://esh.diva-portal.org/smash/get/diva2:1798996/FULLTEXT02.pdf)

-   [Uppdrag Psykisk hälsa: Skolsociala-team-kan-minska-risken-for-utanforskap](https://www.uppdragpsykiskhalsa.se/stockholmslan/barn-unga/goda-exempel/skolsociala-team-kan-minska-risken-for-utanforskap/)

**------------------------------------------------------------------------------**

### Socialt fältarbete
Socialt fältarbete för barn och unga handlar om att arbeta förebyggande genom att vara uppsökande och relationsskapande. Arbetet sker på platser och miljöer där barn och unga befinner sig och handlar om att skapa goda relationer för att kunna identifiera behov och erbjuda stöd och vägledning i barn och ungas vardag. Det kan handla om att ha kontakt med och ge stöd till föräldrar, ge råd om fritidsaktiviteter, eller stötta barn och unga direkt på plats. Genom att fältarbetarna är synliga och tillgängliga i närsamhället skapas en länk mellan invånarna och samhällets stödstrukturer. Förtroendet som byggs upp gör det lättare för individer att söka hjälp och stöd.

Samverkan med andra aktörer är en viktig uppgift där polis, skolor, andra delar av socialtjänsten, elevhälsan och fritidsgårdar är centrala aktörer tillsammans med civilsamhällets aktörer. Detta nätverkande är viktigt för att skapa en helhetsbild av barn och ungas situation och för att samordna samt hänvisa till insatser.

_______________________________________________________________________________________________________________

**Kartläggning**

- Kommunen arbetar med socialt fältarbete. 

-	Det finns en överenskommelse och rutiner för samverkan mellan fältverksamheten och närliggande verksamhet som exempelvis socialtjänstens myndighetsutövning, öppenvård, skola, polis och fritidsverksamheter centralt. 

- Det finns tydliga rutiner, riktlinjer och mål kring vad det sociala fältarbetet bör innehålla och leda till. 

- Det finns en långsiktig finansiering av fältverksamheten.

- Barn och unga involveras i planeringen och genomförandet av organiserade aktiviteter.

- Arbetet med fältverksamheten dokumenteras och följs upp.  

_______________________________________________________________________________________________________________

**Lagstiftning:**

Socialt fältarbete definieras inte i lagtexten men berörs delvis i förarbetena till socialtjänstlagen. Se avsnittet Uppsökande verksamhet och förebyggande arbete, 3 kap. 1 § SoL, 2 § första stycket, 2 § andra stycket.

_______________________________________________________________________________________________________________

**Läs mer om socialt fältarbete**

- [Socialstyrelsen: Socialt fältarbete med barn och unga](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2022-1-7731.pdf)

-   [Kunskapsguiden: Socialt fältarbete med barn och unga](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/uppsokande-och-forebyggande-socialt-arbete/socialt-faltarbete-med-barn-och-unga/)

-   [SKR: Motverka normbrytande beteende och förebyggande socialt fältarbete](https://skr.se/skr/samhallsplaneringinfrastruktur/trygghetsakerhet/brottsforebyggande/barnochungasombegarbrott/tidigaresandningar/motverkanormbrytandebeteendeochforebyggandesocialtfaltarbete.64373.html)


