---
title-block-banner: "#2D6B97"
title-block-banner-color: "#BBDBEC"
title: "Meningsfull fritid"
---

## Definition Skyddsfaktor

Att ha en utvecklande och meningsfull fritid är en viktig del av uppväxttiden som stärker barn och ungas motståndskraft samt främjar fysisk, mental och social utveckling. Fysisk aktivitet, att exempelvis delta i sport och lek, ger stora hälsofördelar såväl fysiskt som psykiskt. En annan viktig friskfaktor är betydelsen av vila, återhämtning och avkoppling. Fritiden är också ett viktigt sammanhang för barn att lära sig sociala färdigheter som samarbete, kommunikation och konflikthantering och blir genom det informella lärandet ett komplement till skolans mer formella lärande. Deltagande i gruppaktiviteter kan bidra till personlig utveckling, en känsla av tillhörighet och sammanhang och vara ett alternativ för barn och unga som annars riskerar bli indragna i riskbeteenden och riskmiljöer. 

Många olika aktörer och verksamheter spelar en viktig roll i att tillhandahålla möjligheter till en meningsfull fritid för barn och unga. Under ungdomsåren blir även andra vuxna, som kommer in i ungas liv genom deras fritid, nya viktiga personer utöver föräldrarna.

## Underlag för verksamhetskartläggning och analys av *meningsfull fritid*


### Barnkonventionen

- **Artikel 6:** Rätt till liv och utveckling.

-	**Artikel 15:** Barn har rätt att delta i föreningar och fredliga sammankomster.

-	**Artikel 23:** Barn med funktionsnedsättning har rätt till ett fullvärdigt och anständigt liv samt hjälp till att aktivt delta i samhället.

-	**Artikel 31:** Barnet har rätt till lek, vila, fritid och rekreation samt fritt delta i det kulturella livet.


### Plan- och bygglagen

**God livsmiljö (2 kap):** PBL föreskriver att planläggning ska ske med hänsyn till natur- och kulturvärden samt miljö- och klimataspekter. Planläggningen ska även främja en estetiskt tilltalande utformning av bebyggelse med närhet till bland annat torg, parker, grönområden och platser för lek och motion samt förebygga olyckor, ohälsa och osäkerhet. Sammanfattningsvis en god livsmiljö tillgänglig och användbar för alla samhällsgrupper.


## Kartläggnings- och fördjupningsfrågor

Frågorna i kartläggningen kan användas som stöd för analys och kvalitetssäkring av främjande och förebyggande verksamheter i kommunen. Med de kartläggande frågorna fångas inte enbart förekomst av en insats eller verksamhet utan även några grundläggande förutsättningar för ett kvalitativt arbete såsom finansiering, långsiktighet och uppföljning. De kartläggande frågorna syns under varje enskild verksamhet men kan även laddas ned här: [Kartläggning av Meningsfull fritid](/Kartläggning_fritid.xlsx) Denna kan ni sedan spara lokalt och arbeta vidare med, till exempel om ni vill jämföra de kartläggande frågorna över tid.

I de fördjupande frågorna kartläggs kvalitén i verksamheten eller insatsen på ett mer djupgående sätt. Frågorna kräver mer detaljerade svar och syftar till att identifiera eventuella utvecklings- och förbättringsområden såsom tillgänglighet, målgruppsanpassning, kompetensutveckling samt tillvägagångssätt för uppföljning. Klicka här för att hämta ner filen: [Dokumentation av fördjupande frågor](/Fördjupningsfrågor_fritid.docx). Denna kan ni sedan spara lokalt och arbeta vidare med.



## Verksamheter och insatser: En meningsfull fritid

Nedan beskrivs verksamheter och insatser som kommuner enligt forskning, myndighetsrekommendationer eller lag kan/ska erbjuda för att stärka skyddsfaktorn *En meningsfull fritid.* Urvalet har förankrats med myndigheter, forskare, experter och kommuner men är inte fullständigt och kan komma att revideras över tid.



### Tidiga, samordnade insatser runt barn och ungdomar

En strukturerad samverkan på flera nivåer i den kommunala organisationen är en förutsättning för att samverkan runt enskilda barn och ungdomar ute i verksamheterna ska fungera. Lika viktig som samverkan runt enskilda barn och unga är att denna samverkan finns kopplat till det främjande och universellt förebyggande arbetet. En strukturerad samverkan är också viktig för att kännedom om verksamheter och insatser ska öka och underlätta hänvisning och information till målgruppen. Vilka aktörer som behöver samverka kan skilja sig åt men förutsättningarna förbättras om en bred samverkan med till exempel förskola/skola, socialtjänst, hälso-och sjukvård (BMM, BVC), elevhälsa, kultur- och fritidsverksamhet, civilsamhälle samt polis finns på plats. 

Samverkan, samarbeten, bidrag och stöd med lokal eller utrustning kan göra fritidsaktiviteter mer tillgängliga för grupper av unga som har sämre förutsättningar att delta i strukturerade aktiviteter. 

_______________________________________________________________________________________________________________

**Kartläggning**

-	Det finns en överenskommelse rörande samordnade insatser runt barn och ungdomar där kultur- och fritidsverksamheten ingår.

-	Det finns plattformar eller forum för tvärsektoriellt arbete där fritids- och föreningsverksamhet ingår.  

-	Det finns mål och strategier för arbetet med samordnade insatser runt barn och ungdomar.

-	Det finns långsiktig finansiering för samordnade insatser runt barn och ungdomar. 

-	Det görs uppföljning av vilka målgrupper som nås genom de samordnade insatserna.

-	Det görs uppföljning av arbetets resultat för barn och ungdomar.

-	Barn och ungdomar involveras i utformningen av insatserna.


_______________________________________________________________________________________________________________

**Läs mer om tidiga och samordnade insatser**

-   [Kunskapsguiden: Om tidiga och samordnade insatser (TSI)](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/)

-   [TSI-boken - Stöd i arbetet med tidiga och samordnade insatser för barn och unga](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2023-10-8779.pdf)

-   [SKR: Kronobarnsmodellen](https://skr.se/skr/halsasjukvard/utvecklingavverksamhet/naravard/nyaarbetssatt/samordningutifranbarnetsfokus.73797.html)

-   [Backa barnet](https://www.backabarnet.se/)

-   [Malmö stad: Communities that care (CTC)](https://malmo.se/Communities-That-Care-CTC.html)

-   [Socialstyrelsen: SSPF (skola, socialtjänst, polis, fritid)](https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/barn-och-unga/unga-som-begar-brott/exempel-brottsforebyggande-metoder/sspf-skola-socialtjanst-polis-fritid/)

-   [MUCF: Samverkan mellan kommun och civilsamhälle. En inspirationsskrift med exempel från sex kommuner](https://www.mucf.se/sites/default/files/2021/06/samverkan_mellan_kommun_och_civilsamhalle.pdf)


**------------------------------------------------------------------------------**

### Fritidshem

Barn ska erbjudas fritidshem upp till 13 års ålder. Enligt skollagen ska fritidshemmet stimulera elevernas utveckling och lärande samt erbjuda dem en meningsfull fritid och rekreation.  Läroplanerna lyfter vidare fram att undervisningen i fritidshemmet ges en vid tolkning där omsorg, utveckling och lärande utgör en helhet. Eleverna bör få vara med och påverka miljön utifrån sina egna behov, intressen och erfarenheter, vilket ger utrymme för både livliga och mer stillsamma aktiviteter i större eller mindre grupper.

Fritidshemmen ingår i skolans systematiska kvalitetsarbete med målsättningen att fritidshemmet ska ge varje elev en meningsfull fritid och en utbildning av hög kvalitet som ger goda möjligheter att utvecklas och lära samt en god grund för fortsatt utbildning. 

Lär mer här: [Skolverket: Nationellt kvalitetssystem](https://www.skolverket.se/skolutveckling/kvalitetsarbete/nationellt-kvalitetssystem)

_______________________________________________________________________________________________________________

**Kartläggning**

-	Verksamheten planeras, följs upp och utvecklas utifrån de nationella målen och läroplan för fritidshem (systematiskt kvalitetsarbete).

-	Verksamheten planeras och anpassas utifrån fysiska, psykiska och/eller andra behov och intressen hos det enskilda barnet eller ungdomen.

-	Verksamheten har planerats eller anpassas utifrån Boverkets riktlinjer om friyta för lek och utevistelse.

-	Barnet och vårdnadshavare erbjuds inflytande över utbildningen i fritidshemmet.

_______________________________________________________________________________________________________________

**Lagstiftning**

*Skollagen 14 kap. 2 §*

[…] Fritidshemmet ska stimulera elevernas utveckling och lärande samt erbjuda dem en meningsfull fritid och rekreation. Utbildningen ska utgå från en helhetssyn på eleven och elevens behov. Fritidshemmet ska främja allsidiga kontakter och social gemenskap. Lag (2022:1315).

*Skollagen kap 5*
Åtgärder för trygghet och studiero i fritidshemmet 

_______________________________________________________________________________________________________________

**Läs mer om fritidshem**

-   [Skolverket: Kvalitet i fritidshem](https://www.skolverket.se/skolutveckling/inspiration-och-stod-i-arbetet/stod-i-arbetet/kvalitet-i-fritidshem)

-   [Skolverket: Fritidshem och öppen fritidsverksamhet](https://www.skolverket.se/regler-och-ansvar/ansvar-i-skolfragor/fritidshem-och-oppen-fritidsverksamhet)

-   [Skolforskningsinstitutet: Meningsfull fritid, utveckling och lärande i fritidshem](https://www.skolfi.se/wp-content/uploads/2021/12/Fritidshem.pdf)

-   [Boverket: Allmänna råd (2015:1) om friyta för lek och utevistelse vid fritidshem](https://www.boverket.se/sv/lag--ratt/forfattningssamling/gallande/fri---bfs-20151/)


**------------------------------------------------------------------------------**

### Öppen ungdoms- och fritidsverksamhet/mötesplatser

Den öppna fritidsverksamheten kännetecknas av att den ordnas under fria former och att unga deltar av egen vilja, ibland är verksamheten mobil eller uppsökande. För öppen fritidsverksamhet som bedrivs enligt skollagen (från 10-13 år) finns lagreglerade kvalitetskrav och krav på uppföljning och utvärdering (se även fritidshem). Därefter kan öppen ungdoms- och fritidsverksamhet tillgängliggöras för unga mellan 13 och 25 år utifrån lokala prioriteringar.

Verksamheten har också en kompenserande roll för barn och unga som inte har råd med fritidsaktiviteter som kostar. Öppen ungdoms- och fritidsverksamhet av kvalitet har ett viktigt främjande uppdrag men kan även erbjuda vuxna förebilder, ett skyddsnät samt säkra alternativ till mer destruktiva miljöer genom att ge unga en plats att vara på efter skolan och under helger. En låg tröskel med trygga vuxna kan också utgöra ett viktigt alternativ till den organiserade föreningsverksamheten. Öppen ungdoms- och fritidsverksamhet kan ha en socialiserande funktion, bidra till personlig utveckling samt fungera som vidareslussning till andra insatser eller föreningsliv. 

_______________________________________________________________________________________________________________

**Kartläggning**

-	Kommunen erbjuder öppen fritidsverksamhet, exempelvis fritidsgårdar, ungdomens hus eller aktivitetshus för barn i åldern 10-13 år. 

-	Kommunen erbjuder öppen ungdoms- och fritidsverksamhet, exempelvis fritidsgårdar, ungdomens hus eller aktivitetshus för barn och ungdomar i åldern 13-25 år. 

-	Det finns strategier för att nå unga med information om de öppna verksamheterna som erbjuds.

-	Det görs uppföljning av vilka målgrupper som deltar i den öppna fritidsverksamheten.

-	Det finns långsiktig finansiering för arbetet med öppen fritidsverksamhet.

-	Verksamheten planeras och anpassas utifrån det enskilda barnet och ungdomen.

-	Riktad verksamhet erbjuds till unga som står långt från deltagande (ex HBTQI, tjejer, unga med funktionsnedsättning)

- Barn och ungdomar inkluderas i utformningen av verksamheten.

_______________________________________________________________________________________________________________

**Lagstiftning**

*Skollagen 25 kap. 4 §*

Den öppna fritidsverksamheten *(från 10-13 år)* ska genom pedagogisk verksamhet komplettera utbildningen i grundskolan, anpassade grundskolan, specialskolan, sameskolan och andra särskilda utbildningsformer i vilka skolplikt kan fullgöras. Verksamheten ska erbjuda barnen möjlighet till utveckling och lärande samt en meningsfull fritid och rekreation.
Lag (2022:1315).

_______________________________________________________________________________________________________________

**Indikatorer**

-	 [Kolada: Ungdomens hus/allaktivitetshus eller motsvarande, antal/10 000 inv 0-18 år (-2023)](https://www.kolada.se/verktyg/jamforaren/?focus=16608&report=92539)

-	[SCB: Medborgarundersökningen - Bra utbud av lekplatser, parklekar etc. i kommunen, andel (%)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__ME__ME0003/)

-	[SCB: Medborgarundersökningen - Bra utbud av ställen för unga att träffas på i kommunen, andel (%)](https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__ME__ME0003/)

_______________________________________________________________________________________________________________

**Läs mer om öppen fritidsverksamhet/mötesplatser**

-   [Forte: Fritidens betydelse för ungas psykiska hälsa ](https://forte.se/publikation/fritidens-betydelse-for-ungas-psykiska-halsa-rattigheter-mojligheter-och-hinder/)

-   [MUCF:Europeiska principer och riktlinjer för lokal öppen fritids- och ungdomsverksamhet](https://www.mucf.se/sites/default/files/2021/10/Chartern_SE.pdf)

-   [MUCF: Ungas fritid](https://www.mucf.se/fritid)

-   [Ung livsstil: Forskningsgrupp som studerar idrott, kultur, fritid och hälsa bland barn och ungdomar](https://www.unglivsstil.org/)

-   [ENCELL: Formellt, icke-formellt och informellt lärande](https://ju.se/center/encell/kunskapsbank/reportage/reportage/2018-01-02-formellt-icke-formellt-och-informellt-larande.html)

-   [Södertörns Högskola: Vägar till en jämlik fritid - En studie om meningsfull fritid och ojämlikt deltagande i Malmö stads fritidsutbud](https://sh.diva-portal.org/smash/get/diva2:1814461/FULLTEXT01.pdf)

-   [Regeringen: Det handlar om livet – nationell strategi inom området psykisk hälsa och suicidprevention](https://www.regeringen.se/contentassets/c162a46e26e4484fa2fddf3e10ff9f01/skr.-2024-25-77.pdf)


**------------------------------------------------------------------------------**

### Bibliotek med barn- och ungdomsverksamhet 

Biblioteket ska vara en mötesplats som är till för alla och som ger tillgång till information, kunskap och kulturupplevelser samt stimulerar och utvecklar läs- och språkkunskaper. Bibliotek kan också fungera som trygga och inkluderande mötesplatser. Bland annat genom barnverksamhet som sagostunder, bokklubbar, läsgrupper och andra organiserade aktiviteter för barn och unga.

Biblioteken bidrar också till språkutveckling och integration, särskilt för nyanlända barn och unga. Genom språkutvecklande aktiviteter och tillgång till litteratur på olika språk, hjälper biblioteken dessa barn att förbättra sina språkkunskaper och anpassa sig till sin nya miljö.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Det finns bibliotek med barn och ungdomsverksamhet i kommunen.

-	Det finns samverkan med andra lokala aktörer som erbjuder barn -och ungdomsverksamhet, såsom öppen fritidsverksamhet, civilsamhällesorganisationer och privata aktörer.

-	Det finns mål och strategier för arbetet med barn och ungdomsverksamheten på biblioteken.

-	Det finns långsiktig finansiering av barn och ungdomsverksamheten på biblioteken.

-	Det görs uppföljning av vilka som besöker barn och ungdomsverksamheten på biblioteken. 

-	Barn och ungdomar inkluderas i utformningen av verksamheten.

_______________________________________________________________________________________________________________

**Lagstiftning**

*Bibliotekslagen 7 §*

Folkbiblioteken ska särskilt främja läsning och tillgång till litteratur.

Folkbiblioteken ska verka för att öka kunskapen om hur informationsteknik kan användas för kunskapsinhämtning, lärande och delaktighet i kulturlivet.

*Bibliotekslagen 8 §*

Folkbiblioteken ska ägna särskild uppmärksamhet åt barn och ungdomar för att främja deras språkutveckling och stimulera till läsning, bland annat genom att erbjuda litteratur utifrån deras behov och förutsättningar.

_______________________________________________________________________________________________________________

**Läs mer om bibliotek med barn- och ungdomsverksamhet**

-   [Region Stockholm: Kunskapsöversikt - Barns och ungas bibliotek](https://www.regionstockholm.se/kultur/regionbiblioteket/kontakt/regionbibliotek-stockholms-publikationer/barns-och-ungas-bibliotek-en-kunskapsoversikt/)

-   [Svensk biblioteksförening: Rekommendationer för folkbibliotekens barn- och ungdomsverksamhet](https://www.biblioteksforeningen.se/rapporter/pa-barn-och-ungdomars-villkor/)

-   [Mediemyndigheten](https://www.mediemyndigheten.se/medie-och-informationskunnighet-mik/natverket-mik-sverige/)

**------------------------------------------------------------------------------**

### Kultur-/musikskola

Kultur- och musikskolan bidrar till barns och ungas välmående genom att erbjuda en plats för kreativt uttryck, personlig utveckling, social sammanhållning och tillit. Genom att delta i gruppaktiviteter och uppträdanden får barn och unga möjlighet att bygga relationer, lära sig samarbeta med andra och motverka social isolering. Verksamheten ska erbjuda en säker och stimulerande miljö där barn och unga kan utforska och utveckla sina intressen.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Kommunen har en eller flera kultur-/musikskolor.

-	Det finns samverkan med andra lokala aktörer som erbjuder ungdomsverksamhet, så som öppen fritidsverksamhet, civilsamhällesorganisationer och privata aktörer. 

-	Det finns mål och strategier för arbetet med kultur-/musikskola.

-	Det finns en utvecklad samverkan mellan skolan och kultur-/musikskolan. 

-	Det finns långsiktig finansiering av kultur-/musikskolans verksamhet.

-	Det görs kontinuerlig uppföljning av vilka som besöker kultur-/musikskolan. 

-	Barn och ungdomar inkluderas i utformningen av verksamheten.

_______________________________________________________________________________________________________________

**Indikatorer**

[Kulturrådet: Statistik om kulturskolor](https://www.kulturradet.se/kulturskolecentrum/statistik/)

[Kolada: Elever i musik- eller kulturskola, 6-19 år, andel (%) ](https://www.kolada.se/verktyg/fri-sokning/)
_______________________________________________________________________________________________________________

**Läs mer om inkluderande kultur-/musikskola**

-   [SKR: Stöd för ökad samverkan mellan skola och kulturskola](https://skr.se/skr/skolakulturfritid/kulturfritid/kulturochmusikskolor/samverkanmellanskolaochkulturskola.9352.html)

-   [Kulturrådet: Kartläggning av samverkan mellan kulturskolan och skola](https://www.kulturradet.se/globalassets/start/kulturskolecentrum/dokument-kulturskolecentrum/samverkan-mellan-skola-och-kulturskola.pdf)

-   [Kulturrådet: Öppen verksamhet i kulturskolan](https://www.kulturradet.se/publikationer/oppen-verksamhet-i-kulturskolan/)

-   [SKR: Fakta om kultur- och musikskolorna](https://skr.se/skr/skolakulturfritid/kulturfritid/kulturochmusikskolor.6968.html)

**------------------------------------------------------------------------------**


### Kostnadsfria lovaktiviteter  

Kostnadsfria lovaktiviteter kan bidra till att skapa en mer jämlik tillgång till meningsfulla fritidsaktiviteter. De kan också bidra till att förebygga exempelvis psykisk ohälsa genom att erbjuda strukturerade och meningsfulla aktiviteter under loven, då barn annars kan vara utan sysselsättning. Dessutom erbjuder dessa aktiviteter en säker miljö där barn kan ha tillgängliga vuxna ledare, vilket minskar risken för att de hamnar i negativa eller destruktiva miljöer. Detta kan vara särskilt viktigt i områden med hög social utsatthet. 

_______________________________________________________________________________________________________________

**Kartläggning**

-	Kommunen erbjuder kostnadsfria lovaktiviteter.

-	Det finns långsiktig finansiering för kostnadsfria lovaktiviteter.

- Verksamheten planeras och anpassas utifrån fysiska, psykiska och/eller andra behov och intressen hos enskilda barnet och ungdomen. 

-	Det görs uppföljning  av vilka målgrupper som deltar i kostnadsfria lovaktiviteter.

-	Det finns mål och strategier för arbetet med kostnadsfria lovaktiviteter.

- Det finns en samverkan med andra förvaltningar i kommunen, och andra lokala aktörer, så som föreningar, privata aktörer eller näringsliv. 

- Barn och ungdomar inkluderas i utformningen av aktiviteterna.

_______________________________________________________________________________________________________________

**Läs mer om kostnadsfria lovaktiviteter**

-   [MUCF: Utvärdering av bidrag till sommarlovsaktiviteter](https://www.mucf.se/sites/default/files/2018/05/bidrag_till_sommarlovsaktiviteter.pdf)

-   [Forte: Fritidens betydelse för ungas psykiska hälsa](hhttps://forte.se/publikation/fritidens-betydelse-for-ungas-psykiska-halsa-rattigheter-mojligheter-och-hinder/)

-   [Södertörn högskola: Studie om meningsfull fritid och ojämlikt deltagande i Malmö stads fritidsutbud ](https://www.mucf.se/sites/default/files/2018/05/bidrag_till_sommarlovsaktiviteter.pdf)

**------------------------------------------------------------------------------**

### Tillgänglig och inkluderande föreningsverksamhet

Det finns betydande skillnader i tillgången till och nyttjandet av fritidsaktiviteter för barn och unga i Sverige. Barn- och unga med socioekonomiska utmaningar, utländsk bakgrund, funktionsnedsättningar, hbtqi-personer samt de som bor i lands- och glesbygd rapporterar i större utsträckning om hinder för att kunna ta del av önskade fritidsaktiviteter.

Inkluderande föreningsverksamhet kännetecknas av tillgänglighet och öppenhet där lokaler ska vara anpassade för alla och information om verksamheten ska spridas brett och vara lätt att förstå. Kommunerna kan exempelvis erbjuda subventionerade eller helt kostnadsfria aktiviteter, ge bidrag till föreningar eller tillhandahålla gratis lokaler och utrustning. Kommunen kan även jobba för samverkan mellan kommunens öppna barn- och ungdomsverksamhet samt föreningslivet. Ledare och instruktörer i föreningsverksamheten kan genomgå regelbunden utbildning i inkluderande pedagogik och ledarskap. Vidare gynnas tillgängligheten av ett nära samarbete med skolor och socialtjänst för att hjälpa till att identifiera barn och unga som kan ha särskilt stor nytta av att delta i föreningsverksamheten.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Kommunen ställer krav på föreningsverksamhet att vara inkluderande.

-	Det finns en samverkansöverenskommelse rörande inkluderande fritid för barn och unga mellan kommunen (skola och fritid) och föreningsverksamhet. 

-	Föreningsverksamhet planeras och anpassas utifrån fysiska, psykiska eller andra behov och intressen hos det enskilda barnet eller ungdomen. 

-	Det görs kontinuerliga uppföljningar av hur föreningsverksamheten lever upp till utformade krav.

-	Det görs uppföljningar av vilka målgrupper som tar del av föreningsverksamheter i kommunen och om identifierade riskgrupper nås.

_______________________________________________________________________________________________________________

**Läs mer om inkluderande föreningsverksamhet**

- [Folkhälsomyndigheten: Fritidskort för barn och unga. ](https://www.folkhalsomyndigheten.se/livsvillkor-levnadsvanor/halsa-i-olika-grupper/barn-och-unga/fritidskort-for-barn-och-ungdomar/)

- [SISU: Trygg och inkluderande idrott](https://utbildning.sisuforlag.se/rfsisu/idrottens-webbar/trygg-och-inkluderande-idrott)

- [Fritidsbanken](https://www.fritidsbanken.se/)

- [MUCF: Samverkan mellan kommun och civilsamhälle. En inspirationsskrift med exempel från sex kommuner](https://www.mucf.se/sites/default/files/2021/06/samverkan_mellan_kommun_och_civilsamhalle.pdf)

- [Centrum för idrottsforskning: Idrotten och (o)jämlikheten – I medlemmarnas eller samhällets intresse?](https://centrumforidrottsforskning.se/kunskap-om-idrott/rapporter/idrotten-och-ojamlikheten-i-medlemmarnas-eller-samhallets-intresse)

- [MFD: Samverka för en aktiv fritid](https://www.mfd.se/verktyg/stod-for-att-framja-en-aktiv-fritid/samverka-for-en-aktiv-fritid/)

- [MUCF: Öppen fritidsverksamhet - om tillgänglighet och inkludering](https://www.mucf.se/verktyg/oppen-fritidsverksamhet-om-tillganglighet-och-inkludering)

- [Göteborgs stad: Skolan som arena ](https://goteborg.se/wps/portal/enhetssida/skola-som-arena/sa-har-arbetar-vi)


**------------------------------------------------------------------------------**


### Socialt fältarbete

Socialt fältarbete för barn och unga handlar om att arbeta förebyggande genom att vara uppsökande och relationsskapande. Arbetet sker på platser och miljöer där barn och unga befinner sig med syftet att kunna identifiera behov och erbjuda stöd och vägledning i barn och ungas vardag. Det kan handla om att ha kontakt med och ge stöd till föräldrar, ge råd om fritidsaktiviteter, eller stötta barn och unga direkt på plats samt länka vidare till hälsofrämjande sammanhang och aktiviteter. Genom att fältarbetarna är synliga och tillgängliga i närsamhället skapas en länk mellan invånarna och samhällets stödstrukturer. Förtroendet som byggs upp gör det lättare för individer att söka hjälp och stöd.

Samverkan med andra aktörer är en viktig uppgift där polis, skolor, andra delar av socialtjänsten, elevhälsan och fritidsgårdar är centrala aktörer tillsammans med civilsamhällets aktörer. Detta nätverkande är viktigt för att skapa en helhetsbild av barn och ungas situation och för att samordna samt hänvisa till insatser.

_______________________________________________________________________________________________________________

**Kartläggning**

- Kommunen arbetar med socialt fältarbete. 

- Det finns en överenskommelse och rutiner för samverkan mellan fältverksamheten och närliggande verksamhet som exempelvis socialtjänstens myndighetsutövning, öppenvård, skola, polis och fritidsverksamheter centralt.

- Det finns tydliga rutiner, riktlinjer och mål kring vad det sociala fältarbetet bör innehålla och leda till. 

- Det finns en långsiktig finansiering av fältverksamheten.

-	Arbetet dokumenteras och följs upp.  

-	Barn och ungdomars synpunkter och behov i inkluderas i utformningen av fältarbetet.

_______________________________________________________________________________________________________________

**Lagstiftning**

Socialt fältarbete definieras inte i lagtexten men berörs delvis i förarbetena till socialtjänstlagen. Se avsnittet Uppsökande verksamhet och förebyggande arbete, 3 kap. 1 § SoL, 2 § första stycket, 2 § andra stycket.

_______________________________________________________________________________________________________________

**Läs mer om socialt fältarbete**

- [Socialstyrelsen: Socialt fältarbete med barn och unga](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2022-1-7731.pdf)

- [Kunskapsguiden: Socialt fältarbete med barn och unga](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/uppsokande-och-forebyggande-socialt-arbete/socialt-faltarbete-med-barn-och-unga/)

- [SKR: Motverka normbrytande beteende och förebyggande socialt fältarbete](https://skr.se/skr/samhallsplaneringinfrastruktur/trygghetsakerhet/brottsforebyggande/barnochungasombegarbrott/tidigaresandningar/motverkanormbrytandebeteendeochforebyggandesocialtfaltarbete.64373.html)

**------------------------------------------------------------------------------**

### Utomhusmiljöer för lek, spontanidrott, friluftsliv och återhämtning

En viktig friskfaktor är vila, återhämtning och avkoppling. Ungas fritid behöver därför även rymma ostrukturerad tid och utrymmen för umgänge utan krav.

En stor del av barn och ungas fritid tillbringas i utomhusmiljöer. Tillgång till grönområden kan bidra till att utjämna skillnaden i hälsa mellan socioekonomiskt svaga och starka grupper, och är särskilt viktigt i tätbebyggda områden. Grönområden ger även möjligheter för kostnadsfria aktiviteter genom exempelvis utegym och bollplaner. I områden med trångboddhet erbjuder även sitt- och grillplatser i utemiljön ett komplement till hemmet och en plats att mötas på.

_______________________________________________________________________________________________________________

**Kartläggning**

•	Det finns tillgängliga, trygga och vardagsnära utomhusmiljöer för varierad, ostrukturerad fritid i kommunen.

•	Det finns mål och strategier för arbetet med utomhusmiljöer för lek, spontanidrott, friluftsliv och återhämtning. 

• Det finns kartlagda naturområden, platser och aktiviteter för fritidsområden tillgängliga i GIS för användning i den lokala planeringen. 

•	Det finns en ändamålsenlig samverkan mellan förvaltningarna i kommunen, med föreningar, privata aktörer eller näringsliv för att utveckla hur utomhusmiljöer används. 

•	Det finns en långsiktig finansiering av underhåll och utveckling av utomhusmiljöer.

•	Det görs uppföljningar av vilka som nyttjar utomhusmiljöer så som parker och naturområden.

•	Barn och ungdomar görs delaktiga i utformningen av utomhusmiljöer.

_______________________________________________________________________________________________________________

**Läs mer om utomhusmiljöer för lek, spontan idrott, friluftsliv och återhämtning**

-   [Regeringen: Mål för friluftslivspolitiken](https://www.regeringen.se/rattsliga-dokument/skrivelse/2012/12/skr.-20121351/)

-   [Forte: Fritidens betydelse för ungas psykiska hälsa – rättigheter, möjligheter och hinder](https://forte.se/publikation/fritidens-betydelse-for-ungas-psykiska-halsa-rattigheter mojligheter-och-hinder/)

- [RISE: Utvärdering av fritidsbanker](https://www.fritidsbanken.se/wp-content/uploads/2020/01/Utvardering-av-fritidsbanker_RISE_rapport.pdf)

- [Naturvårdsverket: Allemansrätten för kommuner](https://www.naturvardsverket.se/vagledning-och-stod/allemansratten/allemansratten-for-kommuner/)

- [Naturvårdsverket: Attraktiv tätortsnära natur](https://www.naturvardsverket.se/amnesomraden/friluftsliv/sveriges-friluftlivsmal/attraktiv-tatortsnara-natur/)

- [Fritidsbanken: Det här säger forskningen om Fritidsbanken](https://www.fritidsbanken.se/det-har-sager-forskningen-om-fritidsbanken/)


