---
title-block-banner: "#2D6B97"
title-block-banner-color: "#BBDBEC"
title: "Måluppfyllelse i skola och förskola"
---

## Definition skyddsfaktor
 
Att klara av skolan är en viktig skyddsfaktor kopplat till flera positiva utfall för barn och unga. Goda studieresultat leder till bättre hälsa samtidigt som god hälsa ger bättre förutsättningar att nå kunskapsmålen. Måluppfyllelse kan även kopplas till minskad risk för negativa utfall, såsom psykisk ohälsa och kriminalitet. 

Både förskolan och skolan har ett kompensatoriskt uppdrag som innebär att skapa förutsättningar för att alla barn ska nå målen med utbildningen och även utveckla färdigheter och egenskaper som behövs för deras övergripande personliga utveckling. En viktig förutsättning för detta är en meningsfull och trygg inlärningsmiljö med goda relationer till vuxna och jämnåriga.

En förskola av hög kvalitet bidra till måluppfyllelse i skolan men har även andra positiva utfall på barns psykiska hälsa samt sociala, kognitiva och språkliga utveckling. De positiva effekterna är som allra störst för barn från familjer med sämre socioekonomiska förutsättningar liksom för barn i behov av särskilt stöd. 
Fler aktörer än förskola och skola kan bidra till måluppfyllelse i skolan, till exempel läsfrämjande insatser på biblioteket, simskola, barnkultur genom kulturskolan, museer eller scenkonsten. Det gäller även psykosociala insatser som utredningar och föräldraskapsstödjande insatser via familjecentraler, socialtjänst eller hälso- och sjukvården.


-   [Skolverket: Hälsa för lärande - lärande för hälsa](https://www.skolverket.se/download/18.2a23c2b1698641e369530/1569845934609/pdf4071.pdf)

-   [Forte: Forskning i korthet – Förskolans roll för att främja psykisk hälsa](https://forte.se/wp-content/uploads/2023/05/fort-0093-fik-maj-2023-ta.pdf)

-   [Folkhälsomyndigheten: Förskolans påverkan på barns hälsa](https://www.folkhalsomyndigheten.se/contentassets/3addb7a81de44a8b8a8f4bfa29b8306c/forskolans-paverkan-barns-halsa-01086.pdf)


## Underlag för verksamhetskartläggning och analys av *måluppfyllelse i förskola/skola*
 
En stor del av insatserna berör förskolan och skolan som verksamheter, eftersom möjligheter att påverka skyddsfaktorn här är stora, detta förutsätter dock att verksamheterna är av hög kvalitet. Studier visar att de viktigaste kvalitetsaspekterna är personalens utbildningsnivå och möjlighet till kompetensutveckling. 

### Det nationella kvalitetssystemet för skolväsendet

Det nationella kvalitetssystemet har arbetats fram av Skolverket i samråd med Specialpedagogiska skolmyndigheten (SPSM), Skolinspektionen och Skolforskningsinstitutet. Kvalitetssystemet är en del av ett regeringsuppdrag och syftar till att skapa samsyn kring vad kvalitet och likvärdighet innebär för skolväsendet. Kvalitetssystemet ska inte vara en parallell process utan underlätta och ingå i det befintliga kvalitetsarbete som görs. Skolmyndigheterna erbjuder även dialogmöten som stöd i arbetet. 

Läs mer här: [Skolverket: Nationellt kvalitetssystem](https://www.skolverket.se/skolutveckling/kvalitetsarbete/nationellt-kvalitetssystem)

I Kvalitetssystemet finns nationella målsättningar, delmål och indikatorer. Även kvalitativa aspekter som kan bidra till att målsättningarna uppfylls beskrivs i ett antal framgångsfaktorer. Framgångsfaktorerna bygger på forskning och annan systematiskt insamlad kunskap och sammanfattar faktorer, förutsättningar och processer som har stor påverkan på kvalitet och likvärdighet i skolväsendet. Framgångsfaktorerna är skolformsövergripande och är möjliga att använda som utgångpunkt i alla skolformer och i fritidshemmet. 

**Framgångsfaktorer** 

-	Förtroendefullt klimat 

-	Hälsofrämjande lärmiljö 

-	Kompensatoriska insatser 

-	Kompetent ledarskap 

-	Professionell utveckling 

-	Systematiskt kvalitetsarbete med undervisningen i fokus 

- Tydlig roll- och ansvarsfördelning

Läs mer här: [Skolverket: Faktorer för framgångsrik skolutveckling - Bilaga: Underlag för självvärdering](https://www.skolverket.se/download/18.3cf0d66d187913b54fe15f5/1684139148009/faktorer-underlag for sjalvvardering-2.pdf)

Denna verksamhetskartläggning kan ses som ett sätt att arbeta med kvalitetssystemet och det som tas fram inom kvalitetssystemet kan bli ett underlag för arbetet med verksamhetskartläggning och analys. I kartläggningen inkluderas fler aktörer och insatser för de mål som kvalitetssystemet också strävar mot. 

### Konventionen om barnets rättigheter

I artikel 28–29 beskrivs barnets rätt till kostnadsfri grundskoleutbildning samt skolans uppdrag att förbereda barn för livet, utveckla respekt för mänskliga rättigheter och fostra i en anda av förståelse, fred, tolerans och vänskap mellan folken.

I artikel 28 beskrivs vikten av skolnärvaro och att åtgärder för att uppmuntra regelbunden närvaro i skolan och minska antalet studieavbrott bör vidtas. I artikel 29 tydliggörs utbildningens flera syften och konventionsstaternas överenskommelse om att barns utbildning ska syfta till att:

(a) utveckla barnets fulla möjligheter i fråga om personlighet, anlag och fysisk och psykisk förmåga,

(b) utveckla respekt för mänskliga rättigheter och grundläggande friheter samt för principerna i Förenta nationernas stadga,

(c) utveckla respekt för barnets föräldrar, för barnets egna kulturella identitet, språk och värden, för bosättningslandets och för ursprungslandets nationella värden och för kulturer som skiljer sig från barnets egen,

(d) förbereda barnet för ett ansvarsfullt liv i ett fritt samhälle i en anda av förståelse, fred, tolerans, jämställdhet mellan könen och vänskap mellan alla folk, etniska, nationella och religiösa grupper och personer som tillhör ett urfolk,

(e) utveckla respekt för naturmiljön.


## Kartläggnings- och fördjupningsfrågor

Frågorna kan användas som stöd vid kartläggning och kvalitetssäkring av främjande och förebyggande verksamheter i kommunen. Med de kartläggande frågorna fångas inte enbart förekomst av en insats eller verksamhet utan även några grundläggande förutsättningar för ett kvalitativt arbete såsom finansiering, långsiktighet och uppföljning. De kartläggande frågorna syns under varje enskild verksamhet men kan även laddas ned här: [Kartläggning av Basutbud Skola](/Kartläggning_skola.xlsx). Denna kan ni sedan spara lokalt och arbeta vidare med, till exempel om ni vill jämföra de kartläggande frågorna över tid.

I de fördjupande frågorna kartläggs kvalitén i verksamheten eller insatsen på ett mer djupgående sätt. Frågorna kräver mer detaljerade svar och syftar till att identifiera eventuella utvecklings- och förbättringsområden såsom tillgänglighet, målgruppsanpassning, kompetensutveckling samt tillvägagångssätt för uppföljning. Klicka här för att hämta ner filen: [Dokumentation av fördjupande frågor](/Fördjupningsfrågor_skola.docx). Denna kan ni sedan spara lokalt och arbeta vidare med.


## Verksamheter och insatser: Måluppfyllelse i förskola och skola

Nedan beskrivs verksamheter och insatser som kommuner enligt forskning, myndighetsrekommendationer eller lag kan/ska erbjuda och som stärker skyddsfaktorn *Måluppfyllelse i skola och förskola*. Urvalet har förankrats med myndigheter, forskare, experter och kommuner men är inte fullständigt och kan komma att revideras över tid.

### Tidiga, samordnade insatser runt barn och ungdomar

En strukturerad samverkan på flera nivåer i den kommunala organisationen är en förutsättning för att samverkan runt enskilda barn och ungdomar ute i verksamheterna ska fungera. En strukturerad samverkan är också viktig för att kännedom om verksamheter och insatser ska öka och underlätta hänvisning och information till målgruppen. Vilka aktörer som behöver samverka kan skilja sig åt men förutsättningarna förbättras om en bred samverkan med till exempel förskola/skola, socialtjänst, hälso-och sjukvård (BMM, BVC), elevhälsa, kultur- och fritidsverksamhet, civilsamhälle samt polis finns på plats

När aktörer och verksamheter runt barn och unga samverkar med varandra så ökar möjligheterna att identifiera och erbjuda relevant stöd i tid. Kunskap från flera verksamheter ger en bättre helhetsbild av barnets eller ungdomens behov av stöd och lämpliga insatser.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Det finns en överenskommelse mellan relevanta aktörer rörande samordnade insatser för barn och ungdomar där förskola, skola och elevhälsan ingår.

-	Det finns plattformar eller forum för tvärsektoriellt arbete där förskola, skola och elevhälsan ingår. 

-	Det finns mål och strategier för arbetet med samordnade insatser runt barn och ungdomar.

-	Det finns långsiktig finansiering för samordnade insatser runt barn och ungdomar. 

-	Det görs uppföljning av vilka målgrupper som nås genom de samordnade insatserna.

-	Det görs uppföljning av arbetets resultat för barn och ungdomar.

-	Barn, ungdomar och föräldrar involveras i utformningen av insatserna.

_______________________________________________________________________________________________________________

**Läs mer om samordnade insatser runt barn och ungdomar**

-   [SKR: Kronobarnsmodellen](https://skr.se/skr/halsasjukvard/utvecklingavverksamhet/naravard/nyaarbetssatt/samordningutifranbarnetsfokus.73797.html)

-   [Kunskapsgudien: Om tidiga och samordnade insatser (TSI)](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/)

-   [TSI-boken - Stöd i arbetet med tidiga och samordnade insatser för barn och unga](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2023-10-8779.pdf)

-   [Kunskapsguiden: Skottlandsmodellen](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/skottlandsmodellen/)

-   [Backa barnet](https://www.backabarnet.se/)

-   [Malmö stad: Communities that care (CTC)](https://malmo.se/Communities-That-Care-CTC.html)

-   [Socialstyrelsen: SSPF (skola, socialtjänst, polis, fritid)](https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/barn-och-unga/unga-som-begar-brott/exempel-brottsforebyggande-metoder/sspf-skola-socialtjanst-polis-fritid/)

**------------------------------------------------------------------------------**

### Öppen förskola
Öppen förskola är en pedagogisk verksamhet för barn samt medföljande förälder, dagbarnvårdare eller annan vuxen. Den fungerar som en mötesplats där barn kan leka och delta i olika aktiviteter under pedagogisk ledning, samtidigt som föräldrarna kan träffa andra vuxna, utbyta erfarenheter och få stöd i sitt föräldraskap. Öppna förskolan är en verksamhet med låga trösklar och därför även en viktig arena för informationsinsatser för att öka deltagandet i förskolan för barn med utländsk bakgrund.

Öppna förskolor finansieras oftast av kommunen och kan vara samlokaliserad i en familjecentral. 

_______________________________________________________________________________________________________________

**Kartläggning**

- Det finns en eller flera öppna förskolor i kommunen.

- Det finns mål och strategier för arbetet med öppen förskola.

- Det finns långsiktig finansiering av den öppna förskolan.

- Det finns samverkansöverenskommelser mellan öppna förskolan och andra närliggande verksamheter.

- Det görs kontinuerlig uppföljning av vilka som besöker den öppna förskolan.

- Besökare inkluderas i utformning av innehållet i verksamheten. 

_______________________________________________________________________________________________________________

**Lagstiftning**

*Skollagen 25 kap. 3 §*

Den öppna förskolan ska erbjuda barn en pedagogisk verksamhet i samarbete med de till barnen medföljande vuxna, samtidigt som de vuxna ges möjlighet till social gemenskap.


**Indikatorer**

-   [Kolada: Antal öppna förskolor, samt varav på familjecentral, i relation till antal barn 0-6 år per län och kommun](https://www.kolada.se/verktyg/fri-sokning/?kpis=148817&years=30200,30199,30198&municipals=82304&rows=municipal,kpi&visualization=bar-chart)

_______________________________________________________________________________________________________________

**Läs mer om öppen förskola**

-   [Myndigheten för familjerätt och föräldraskapsstöd: Öppen förskola](https://www.mfof.se/foraldraskapsstod/arenor-for-foraldraskapsstod/oppen-forskola.html)

-   [Skolverket; Allmänna råd för öppen förskola](https://www.skolverket.se/download/18.6bfaca41169863e6a6538f8/1553956773578/pdf607.pdf)

-   [SKR: Öppen förskola – tillsammans för jobb och integration](https://skr.se/skr/skolakulturfritid/forskolagrundochgymnasieskolakomvux/oppenforskolaforsprakochintegration.46558.html)

**------------------------------------------------------------------------------**

### Närvarofrämjande arbete

Att vara närvarande i förskola och skola är en grundläggande förutsättning för skyddsfaktorn *Måluppfyllelse i förskola och skola*. Det handlar i stor utsträckning om hur eleverna trivs i förskola och skola, men skolfrånvaro kan även förklaras av familjeförhållanden eller behov av stöd och vård hos eleven som inte tillgodosetts. Även goda relationer mellan elever och lärare samt mellan hem och förskola/skola är av stor betydelse för närvaron.

_______________________________________________________________________________________________________________

**Kartläggning**

•	Kommunen arbetar uppsökande avseende de barn 3-5 år som inte är inskrivna i förskolan. 

•	Kommunen redovisar skillnader i närvaro för olika socioekonomiska områden.

•	Närvarodata- och frånvarostatistik används som en utgångspunkt vid planering och resursfördelning.

•	Det finns en kommunövergripande plan samt rutiner för närvarofrämjande arbete.

•	Det finns kommunövergripande rutiner om frånvaroutredningar.

•	Det finns tydliga rutiner för samarbetet med till exempel socialtjänsten och hälso- och sjukvården, däribland barn- och ungdomspsykiatrin (BUP).

•	All skolpersonal och elevhälsan involveras i det närvarofrämjande arbetet.

•	Barn, ungdomar och föräldrar involveras i det närvarofrämjande arbetet.

_______________________________________________________________________________________________________________

**Indikatorer**

- [Kolada: Skolfrånvaro, andel elever över x % (15-20)](https://www.kolada.se/)

- Barn 3-5 år inskrivna i förskola, andel %. Här kan du söka statistik om inskrivna i förskola hos Skolverket [Skolverket: Sök statistik ](https://www.skolverket.se/skolutveckling/statistik/sok-statistik-om-forskola-skola-och-vuxenutbildning?sok=SokC&verkform=F%C3%B6rskola&omrade=Barn%20och%20grupper&lasar=2023&run=1)

_______________________________________________________________________________________________________________

**Lagstiftning**

*Skollagen 7 kap. 19 a §*
Om en elev har upprepad eller längre frånvaro från den verksamhet som avses i 17 § ska rektorn, oavsett om det är fråga om giltig eller ogiltig frånvaro, se till att frånvaron skyndsamt utreds om det inte är obehövligt. Utredningen ska genomföras i samråd med eleven och elevens vårdnadshavare samt med elevhälsan.

*Skollagen 7 kap. 22 §*
Huvudmannen ska se till att eleverna i huvudmannens förskoleklass, grundskola och anpassad grundskola fullgör sin skolgång.

Se även *Skollagen 8 kap. 12 a §* och *Skollagen 29 kap 19 §* samt proposition 2021/22:132.

Läs mer här: [Skolverket: Kommuners arbete för fler barn i förskolan](https://www.skolverket.se/skolutveckling/leda-och-organisera-skolan/uppsokande-verksamhet-och-tillsyn-av-forskolor/kommuners-arbete-for-fler-barn-i-forskolan)

_______________________________________________________________________________________________________________

**Läs mer om närvarofrämjande arbete**

-   [Skolverket: Rekommendationer för arbetet med att främja närvaro samt förebygga och åtgärda frånvaro](https://www.skolverket.se/skolutveckling/inspiration-och-stod-i-arbetet/rekommendationer/rekommendationer-framja-narvaro-och-forebygga-franvaro)

-   [Ifous fokuserar: Skolnärvaro](https://ifous.se/ifous-fokuserar-skolnarvaro/)

-   [Skolverket: Webinarium om att förebygga skolfrånvaro](https://youtu.be/vxFvflq_DQw)

-   [Socialstyrelsen: SAMS - Samverkan för placerade barn och ungas kontinuerliga skolgång](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2024-6-9176.pdf)

-   [Skolverket: Kommunens aktivitetsansvar för ungdomar (KAA)](https://www.skolverket.se/skolutveckling/leda-och-organisera-skolan/organisera-for-fortsatta-studier-och-arbetsliv/kommunernas-aktivitetsansvar--for-ungdomar)

**------------------------------------------------------------------------------**

### Samverkan förskola/skola och föräldrar

Föräldrars engagemang i barnets skolgång samt hur hemmiljön fungerar är några av de största påverkansfaktorerna för barns måluppfyllelse i skolan. En god samverkan mellan förskola/skola och föräldrar är därför centralt i arbetet med att öka måluppfyllelse i skolan. 

Förskola, skola och fritidshemmet är verksamheter som möter majoriteten av alla föräldrar och barn under större delen av barnens uppväxt. Både förskola och skola är därför viktiga arenor för samverkan med och stöd till föräldrar. Enligt Skolverket kan skolan erbjuda information och stödjande samtal från elevhälsan samt mer kontinuerliga avstämningar mellan förskola/fritidshemmet och förälder vid lämningar och hämtningar. Även föräldraskapsstödsprogram kan erbjudas via förskola och skola och utföras av utbildad personal från förskolan, skolan, elevhälsan, socialtjänsten eller liknande.

I skolans systematiska kvalitetsarbete ingår att löpande utveckla och utvärdera samverkan med föräldrar och vårdnadshavare för att säkerställa att man når ut till alla.

_______________________________________________________________________________________________________________

**Kartläggning**

-	Det finns en kommunövergripande plan för förskolans, skolans och fritidshemmets samverkan med föräldrar.

- Kommunen erbjuder personalen kunskapshöjande insatser om föräldraskapsstöd och föräldrasamverkan.

- Respektive förskola/skola/fritidshem har en gemensam strategi för att möjliggöra för hem och vårdnadshavare att bli delaktiga i frågor som rör elevens skolgång.

- Respektive förskola/skola/fritidshem har gemensamma förhållningssätt i kontakter med vårdnadshavare och hemmen.

_______________________________________________________________________________________________________________

**Lagstiftning**

*Skollagen 1 kap. 4 §*
Utbildningen syftar också till att i samarbete med hemmen främja barns och elevers allsidiga personliga utveckling till aktiva, kreativa, kompetenta och ansvarskännande individer och medborgare.

_______________________________________________________________________________________________________________

**Läs mer om samverkan mellan förskola/skola och föräldrar**

-   [SKR: Synligt lärande - Presentation av en studie om vad som påverkar elevers studieresultat](https://skr.se/download/18.7c1c4ddb17e3d28cf9ba687f/1643196854985/7164-706-1.pdf)

-   [Skolverket: Skolan och hemmet - exempel och forskning om lärares samarbete med elevernas vårdnadshavare](https://www.skolverket.se/publikationsserier/stodmaterial/2015/skolan-och-hemmet)

-   [Skolverket: Checklista för att utveckla vår skolas samverkan med hem och vårdnadshavare ](https://www.skolverket.se/download/18.3cf0d66d187913b54fe15f6/1684141494320/checklista-utveckla-samverkan-1.pdf)

-   [Specialpedagogiska skolmyndigheten (SPSM): Samarbete och kommunikation för elevernas bästa](https://www.spsm.se/systematik-for-tidiga-stodinsatser/del-4---att-prova-och-omprova-tillsammans/samarbete-och-kommunikation-for-elevernas-basta/)

-   [Specialpedagogiska skolmyndigheten (SPSM): Samverkan för lärande](https://spsm.se/studiepaket-amnesomraden/moment-3/)

**------------------------------------------------------------------------------**

### Skolsociala team
Skolsociala team har ett tvärprofessionellt arbetssätt där socialtjänst och skola samverkar för att öka trygghet, skolnärvaro och måluppfyllelse samt ge elever med en ogynnsam utveckling stöd i ett tidigt skede. Skolsociala team kan till exempel erbjuda stödinsatser till vårdnadshavare och underlätta kommunikation och samarbete mellan vårdnadshavare och övriga aktörer som finns runt den enskilda eleven som till exempel hälso- och sjukvård och fritidssektor.

_______________________________________________________________________________________________________________

**Kartläggning**

- Det finns skolsociala team i kommunen.

- Det finns mål och strategier för arbetet med skolsociala team.

-	Det finns en långsiktig finansiering för arbetet med skolsociala team.

-	Barn och föräldrar inkluderas i arbetet med de skolsociala teamen.

-	Det görs uppföljning av vilka målgrupper som får insatser via skolsociala team.

-	Det görs uppföljning av vilket resultat skolsociala team får för barn och föräldrar.

_______________________________________________________________________________________________________________

**Lagstiftning**

Skolans elevhälsoarbete stärktes i skollagen 2023. Det innebär bland annat att elevhälsan vid behov ska samverka med hälso- och sjukvården och socialtjänsten.

Läs mer här: [Kunskapsguiden: Vägledning för elevhälsan ](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/vagledning-for-elevhalsa/)

_______________________________________________________________________________________________________________

**Läs mer om skolsociala team**

- [Skolverket: Starta och arbeta med skolsociala team](https://www.skolverket.se/skolutveckling/leda-och-organisera-skolan/ge-extra-stod-till-elever/starta-och-arbeta-med-skolsociala-team)

- [Marie Cederschiöld högskola: Att arbeta med skolsociala team - Utvärdering av innehåll och arbetssätt i Stockholm stad](https://esh.diva-portal.org/smash/get/diva2:1798996/FULLTEXT02.pdf)

- [Uppdrag Psykisk hälsa: Skolsociala-team-kan-minska-risken-for-utanforskap](https://www.uppdragpsykiskhalsa.se/stockholmslan/barn-unga/goda-exempel/skolsociala-team-kan-minska-risken-for-utanforskap/)

**------------------------------------------------------------------------------**

### Kunskapsbaserade insatser och program i förskola och skola

Barns måluppfyllelse i förskola samt skola är starkt kopplat till deras mående och trivsel i verksamheten samt vice versa. Utöver det kvalitetsarbete som görs inom skolväsendet och som även syftar till att främja barns välmående så finns kunskapsbaserade insatser och program som fokuserar på bemötande och förhållningssätt hos pedagoger och lärare och vars effekter går att utvärdera i relation till mer specifika utfall.  

_______________________________________________________________________________________________________________

**Kartläggning**

- Förskolorna i vår kommun erbjuder kunskapsbaserade insatser för att främja barns trygghet och/eller hälsa. Exempelvis:

  - Promoting Alternative Thinking Strategies (PATHS)
  - [Liten och Trygg](https://www.jagvillveta.se/for-dig-som-vuxen/)

- Skolorna i vår kommun erbjuder kunskapsbaserade insatser för att främja barns trygghet och/eller hälsa. Exempelvis:

  *Psykisk hälsa/suicidprevention*

  - [YAM Youth Aware of Mental health](https://www.chis.regionstockholm.se/nasp/utbildning/youth-aware-mental-health/)
  
  -	[PAX i skolan](https://paxiskolan.se/) och [Höjaspelet](https://malmo.se/Communities-That-Care-CTC/Hojaspelet---Good-Behavior-Game.html) (varianter av Good Behavior Game)
  
  - [WINST](https://atstorning.se/internetbaserad-hjalp/) – webkurs för att förebygga ätstörningar.
  
  - [IBIS Inkluderande Beteendestöd I Skolan](https://pedagog.uppsala.se/resurser-for-undervisning/ibis-for-grundskolan/)
  
  - [FRIENDS](https://friendsresilience.org/about)
  
  - [SEL-program (Social Emotional Learning)](https://www.sbu.se/sv/publikationer/SBU-utvarderar/framjande-av-psykiskt-valbefinnande-hos-barn-och-ungdomar2/)
  
  - [Rörelsesatsning i skolan](https://www.rf.se/rf-arbetar-med/aktuella-satsningar/rorelsesatsning-i-skolan)
  
  *Trygghetsfrämjande/våldsförebyggande*

  - [Olweusprogrammet](https://olweus.se/) mot mobbning
  
  - [Mentors in Violence Prevention (MVP)](https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/barn-och-unga/unga-som-begar-brott/exempel-brottsforebyggande-metoder/mvp-mentorer-i-valdsprevention-mentors-in-violence-prevention/)
  
  - [TÅGET](https://www.socialstyrelsen.se/kunskapsstod-och-regler/omraden/barn-och-unga/unga-som-begar-brott/exempel-brottsforebyggande-metoder/taget/)
  
  - [KiVa Skola](https://sverige.kivaprogram.net/partnership/)
  
  - [Tryggare skola](hhttps://tryggaresverige.org/skola/tryggare-skola) 
  
  - Skol-Komet
  
  *Normkritik och inkludering*

  - [RFSL:	Hbtqi-certifiering](https://rfslutbildning.se/hbtqi-certifiering/) 
  
  - [Machofabriken](https://machofabriken.se/) 
  
  - [Lås upp](hhttps://www.lasupp.se/) 

-	Det finns mål och strategier för arbetet med de kunskapsbaserade insatserna.

-	Det finns långsiktig finansiering för de kunskapsbaserade insatserna.

-	Det finns struktur för de kunskapsbaserade insatserna (exempelvis återkommande utbildning av pedagoger, samordnare och kompetensutveckling).  

- Det görs uppföljning av vilka resultat som insatserna får för barnen.

_______________________________________________________________________________________________________________

**Indikatorer**

- [Kommunrapport: Andel elever som känner sig trygga i skolan](https://pgmj.github.io/DIDsteg2/www.kolada.se)

_______________________________________________________________________________________________________________

**Läs mer om kunskapsbaserade insatser i förskola och skola**

- [Risk och skyddsfaktorer – vad vet vi och vad kan göras med kunskapen?](https://osf.io/ntcw3)

- [SBU: program-for-att-forebygga-psykisk-ohalsa-hos-barn](https://www.sbu.se/sv/publikationer/SBU-utvarderar/program-for-att-forebygga-psykisk-ohalsa-hos-barn2/)

- [Ifous fokuserar: Att främja psykisk hälsa och motverka psykisk ohälsa i förskola](https://ifous.se/ifous-fokuserar-psykisk-halsa-i-forskola/)

- [Brottsoffermyndigheten: Liten och trygg](https://www.jagvillveta.se/for-dig-som-vuxen/)

- [BRÅ: Effekter av anti-mobbningsprogram - vad säger forskningen?](https://bra.se/publikationer/arkiv/publikationer/2009-03-30-effekter-av-anti-mobbningsprogram---vad-sager-forskningen.html)

- [Skolverket: Positivt samband mellan rörelse i skolan och lärande](https://www.skolverket.se/skolutveckling/forskning-och-utvarderingar/artiklar-om-forskning/positivt-samband-mellan-rorelse-i-skolan-och-larande)

- [Elevhälsoportalen](http://www.elevhalsoportalen.se/)

**------------------------------------------------------------------------------**

### Socialt fältarbete
Socialt fältarbete för barn och unga handlar om att arbeta förebyggande genom att vara uppsökande och relationsskapande. Arbetet sker på platser och miljöer där barn och unga befinner sig med syftet att kunna identifiera behov och erbjuda stöd och vägledning i barn och ungas vardag. Det kan handla om att ha kontakt med och ge stöd till föräldrar, ge råd om fritidsaktiviteter, eller stötta barn och unga direkt på plats. Genom att fältarbetarna är synliga och tillgängliga i närsamhället skapas en länk mellan invånarna och samhällets stödstrukturer. Förtroendet som byggs upp gör det lättare för individer att söka hjälp och stöd.

Samverkan med andra aktörer är en viktig uppgift där polis, skolor, andra delar av socialtjänsten, elevhälsan och fritidsgårdar är centrala aktörer tillsammans med civilsamhällets aktörer. Detta nätverkande är viktigt för att skapa en helhetsbild av den unges situation och för att samordna samt hänvisa till insatser.

_______________________________________________________________________________________________________________

**Kartläggning**

- Kommunen arbetar med socialt fältarbete. 

- Det finns en överenskommelse och rutiner för samverkan mellan fältverksamheten och närliggande verksamhet som exempelvis socialtjänstens myndighetsutövning, öppenvård, skola, polis och fritidsverksamheter centralt.

- Det finns tydliga rutiner, riktlinjer och mål kring vad det sociala fältarbetet bör innehålla och leda till. 

- Det finns en långsiktig finansiering av fältverksamheten.

-	Arbetet dokumenteras och följs upp.  

-	Barn och ungdomars synpunkter och behov i inkluderas i utformningen av fältarbetet.

_______________________________________________________________________________________________________________

**Lagstiftning**

Socialt fältarbete definieras inte i lagtexten men berörs delvis i förarbetena till socialtjänstlagen. Se avsnittet Uppsökande verksamhet och förebyggande arbete, 3 kap. 1 § SoL, 2 § första stycket, 2 § andra stycket.

_______________________________________________________________________________________________________________

**Läs mer om socialt fältarbete**

- [Socialstyrelsen: Socialt fältarbete med barn och unga](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2022-1-7731.pdf)

-   [Kunskapsguiden: Socialt fältarbete med barn och unga](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/uppsokande-och-forebyggande-socialt-arbete/socialt-faltarbete-med-barn-och-unga/)

-   [SKR: Motverka normbrytande beteende och förebyggande socialt fältarbete](https://skr.se/skr/samhallsplaneringinfrastruktur/trygghetsakerhet/brottsforebyggande/barnochungasombegarbrott/tidigaresandningar/motverkanormbrytandebeteendeochforebyggandesocialtfaltarbete.64373.html)

**------------------------------------------------------------------------------**

## Ytterligare lästips uppdelade på verksamhet

### Förskola av hög kvalitét

-   [Förskolans påverkan på barns hälsa](https://www.folkhalsomyndigheten.se/contentassets/3addb7a81de44a8b8a8f4bfa29b8306c/forskolans-paverkan-barns-halsa-01086.pdf)

-   [Ifous fokuserar: Att främja psykisk hälsa och motverka psykisk ohälsa i förskola](https://ifous.se/ifous-fokuserar-psykisk-halsa-i-forskola/)

-   [Hälsa för lärande – lärande för hälsa](https://www.skolverket.se/publikationsserier/forskning-for-skolan/2019/halsa-for-larande---larande-for-halsa)

### Läsfrämjande insatser

-   [Läsning på gång!](https://wwwbiblioteksfor.cdn.triggerfish.cloud/uploads/2021/09/lasning-pa-gang-webb.pdf)

-   [Dags att höja ribban! Samverkan för små barns språkutveckling](https://regionhalland.se/app/uploads/2019/03/dags-att-hoja-ribban-2017-webb.pdf)

-   [Insatser för att stärka barns och elevers läsande](https://www.skolverket.se/publikationsserier/regeringsuppdrag/2022/insatser-for-att-starka-barns-och-elevers-lasande)

-   [Kulturrådet och Skolverket i gemensam satsning på högläsning i förskolan](https://www.skolverket.se/om-oss/aktuellt/nyheter/nyheter/2022-08-24-kulturradet-och-skolverket-i-gemensam-satsning-pa-hoglasning-i-forskolan)

-   [Så kan du stärka elevers läsning](https://www.skolverket.se/skolutveckling/inspiration-och-stod-i-arbetet/stod-i-arbetet/sa-kan-du-starka-elevers-lasning)

-   [Viktigt att skapa stimulerande läsmiljöer i förskolan](https://www.skolverket.se/skolutveckling/forskning-och-utvarderingar/artiklar-om-forskning/viktigt-att-skapa-stimulerande-lasmiljoer-i-forskolan)

-   [Läsfrämjande arbete i grundskolan](https://www.skolinspektionen.se/beslut-rapporter-statistik/publikationer/kvalitetsgranskning/2022/lasframjande-arbete-i-grundskolan/)

-   [Stödja och stimulera kommunikations- och språkutveckling bland barn 0 till 2 år - Ett kunskapsstöd för barnhälsovården](https://www.socialstyrelsen.se/globalassets/sharepoint-dokument/artikelkatalog/ovrigt/2022-3-7794.pdf)


### Trygga skolövergångar

-   [Positiva kamratrelationer är en skyddsfaktor vid skolövergångar](https://www.skolverket.se/skolutveckling/forskning-och-utvarderingar/artiklar-om-forskning/positiva-kamratrelationer-ar-en-skyddsfaktor-vid-skolovergangar)

-   [Lärares roll och utmaningar i arbetet med barns tidiga skolövergångar](https://mdh.diva-portal.org/smash/record.jsf?pid=diva2%3A1621860&dswid=-8160)


### Närvarofrämjande arbete

-   [Handlingsplan vid skolfrånvaro – så här gör du](https://www.folkhalsan.fi/globalassets/unga/professionella/skolfranvaro/fh_skolfranvaro_handlingsplan.pdf)

-   [Förebygga skolfrånvaro](https://kunskapsguiden.se/omraden-och-teman/barn-och-unga/tidiga-och-samordnade-insatser-tsi/forebygga-skolfranvaro/)


### Hälsofrämjande insatser

-   [Mer rörelse i skolan](https://www.skolverket.se/skolutveckling/inspiration-och-stod-i-arbetet/stod-i-arbetet/mer-rorelse-i-skolan)

-   [Främjande av psykiskt välbefinnande hos barn och ungdomar](https://www.sbu.se/sv/publikationer/SBU-utvarderar/framjande-av-psykiskt-valbefinnande-hos-barn-och-ungdomar/)

-   [Slutbetänkande av Kommittén för främjande av ökad fysisk aktivitet](https://generationpep.se/sv/aktuellt/slutbetankande-kommitten-2023/)

-   [Hälsa för lärande – lärande för hälsa](https://www.skolverket.se/publikationsserier/forskning-for-skolan/2019/halsa-for-larande---larande-for-halsa)

-   [Hälsofrämjande perspektiv i förskolan viktigt för hela livet](https://www.skolverket.se/skolutveckling/forskning-och-utvarderingar/artiklar-om-forskning/halsoframjande-perspektiv-i-forskolan-viktigt-for-hela-livet)

-   [Kraftsamling för ungas psykiska hälsa - Kunskapssammanfattning och förslag till interventioner från Svenska Läkaresällskapet arbetsgrupp 2021](https://www.sls.se/globalassets/sls/dokument/rapport-kraftsamling-for-ungas-psykiska-halsa-20210521.pdf)
